# 食谱库 - 冠之今天吃什么
# 100+ 道常见家常菜，每道包含完整食材、调料、步骤、营养数据

RECIPES = [
    # ============================
    # 猪肉类（约 15 道）
    # ============================
    {
        "id": "p001", "name": "青椒炒肉", "category": "猪肉类",
        "description": "经典家常下饭菜，青椒爽脆，肉片嫩滑",
        "emoji": "🫑🥩", "prepTime": 10, "cookTime": 10,
        "ingredients": [
            {"name": "青椒", "amount": 200, "unit": "g"},
            {"name": "猪肉", "amount": 200, "unit": "g"},
            {"name": "大蒜", "amount": 10, "unit": "g"},
            {"name": "生姜", "amount": 5, "unit": "g"},
        ],
        "seasonings": [
            {"name": "生抽", "amount": 15, "unit": "ml"},
            {"name": "老抽", "amount": 5, "unit": "ml"},
            {"name": "料酒", "amount": 10, "unit": "ml"},
            {"name": "淀粉", "amount": 5, "unit": "g"},
            {"name": "盐", "amount": 3, "unit": "g"},
            {"name": "食用油", "amount": 20, "unit": "ml"},
        ],
        "steps": [
            "猪肉切薄片，加料酒、生抽、淀粉腌制10分钟",
            "青椒去籽切块，大蒜切片，生姜切末",
            "锅中倒油烧热，下肉片滑炒至变色盛出",
            "锅中留底油，爆香蒜片姜末",
            "下青椒翻炒至断生，约2分钟",
            "倒回肉片，加生抽、老抽、盐翻炒均匀即可出锅",
        ],
        "tags": ["下饭", "快手菜", "一人食", "经典"],
        "healthStars": 4, "dietFriendly": True, "dietNote": "瘦肉为主，青椒低热量，少油少盐可做减脂餐",
        "nutrition": {"calories": 280, "salt": 2.5, "protein": "高蛋白"},
    },
    {
        "id": "p002", "name": "鱼香肉丝", "category": "猪肉类",
        "description": "酸甜微辣，鱼香味型经典川菜，超级下饭",
        "emoji": "🥩🥕", "prepTime": 15, "cookTime": 10,
        "ingredients": [
            {"name": "猪里脊", "amount": 250, "unit": "g"},
            {"name": "胡萝卜", "amount": 100, "unit": "g"},
            {"name": "木耳", "amount": 50, "unit": "g"},
            {"name": "青椒", "amount": 100, "unit": "g"},
            {"name": "大蒜", "amount": 10, "unit": "g"},
        ],
        "seasonings": [
            {"name": "生抽", "amount": 15, "unit": "ml"},
            {"name": "醋", "amount": 15, "unit": "ml"},
            {"name": "白糖", "amount": 10, "unit": "g"},
            {"name": "豆瓣酱", "amount": 15, "unit": "g"},
            {"name": "淀粉", "amount": 10, "unit": "g"},
            {"name": "料酒", "amount": 10, "unit": "ml"},
            {"name": "盐", "amount": 2, "unit": "g"},
            {"name": "食用油", "amount": 25, "unit": "ml"},
        ],
        "steps": [
            "猪里脊切丝，加料酒、淀粉、少许盐腌制10分钟",
            "胡萝卜、青椒切丝，木耳泡发切丝，蒜切末",
            "调鱼香汁：生抽+醋+糖+淀粉+少量水调匀",
            "热锅凉油，下肉丝滑炒至变色盛出",
            "锅中加油，下豆瓣酱炒出红油，爆香蒜末",
            "下胡萝卜丝、木耳丝、青椒丝翻炒2分钟",
            "倒回肉丝，淋入鱼香汁，大火收汁翻匀出锅",
        ],
        "tags": ["下饭", "经典", "川菜", "多人食"],
        "healthStars": 3, "dietFriendly": False, "dietNote": "含糖含油偏高，减肥期间建议少食",
        "nutrition": {"calories": 350, "salt": 3.0, "protein": "高蛋白"},
    },
    {
        "id": "p003", "name": "回锅肉", "category": "猪肉类",
        "description": "肥而不腻，蒜香浓郁，川菜之首，米饭杀手",
        "emoji": "🥓🧄", "prepTime": 10, "cookTime": 15,
        "ingredients": [
            {"name": "五花肉", "amount": 300, "unit": "g"},
            {"name": "青椒", "amount": 200, "unit": "g"},
            {"name": "大蒜", "amount": 30, "unit": "g"},
            {"name": "生姜", "amount": 10, "unit": "g"},
            {"name": "葱", "amount": 20, "unit": "g"},
        ],
        "seasonings": [
            {"name": "豆瓣酱", "amount": 20, "unit": "g"},
            {"name": "生抽", "amount": 10, "unit": "ml"},
            {"name": "料酒", "amount": 15, "unit": "ml"},
            {"name": "白糖", "amount": 5, "unit": "g"},
            {"name": "食用油", "amount": 15, "unit": "ml"},
            {"name": "盐", "amount": 1, "unit": "g"},
        ],
        "steps": [
            "五花肉整块冷水下锅，加姜片料酒煮20分钟至八成熟",
            "捞出放凉，切薄片（越薄越好）",
            "青椒切块，大蒜切段，姜切片",
            "热锅少油，下肉片中小火煸炒至出油卷曲",
            "下豆瓣酱炒出红油，加姜片翻匀",
            "下青椒块和大蒜段翻炒至断生",
            "加生抽、白糖、盐翻匀即可（豆瓣酱咸，盐要少放）",
        ],
        "tags": ["下饭", "经典", "川菜", "多人食"],
        "healthStars": 3, "dietFriendly": False, "dietNote": "五花肉脂肪含量高，减肥期间不建议频繁食用",
        "nutrition": {"calories": 520, "salt": 3.2, "protein": "高蛋白"},
    },
    {
        "id": "p004", "name": "红烧肉", "category": "猪肉类",
        "description": "色泽红亮，肥而不腻，入口即化，国民硬菜",
        "emoji": "🥓🍖", "prepTime": 10, "cookTime": 50,
        "ingredients": [
            {"name": "五花肉", "amount": 500, "unit": "g"},
            {"name": "生姜", "amount": 15, "unit": "g"},
            {"name": "葱", "amount": 20, "unit": "g"},
        ],
        "seasonings": [
            {"name": "生抽", "amount": 20, "unit": "ml"},
            {"name": "老抽", "amount": 15, "unit": "ml"},
            {"name": "料酒", "amount": 20, "unit": "ml"},
            {"name": "白糖", "amount": 20, "unit": "g"},
            {"name": "食用油", "amount": 20, "unit": "ml"},
        ],
        "steps": [
            "五花肉切3cm方块，冷水入锅焯水去浮沫，捞出洗净",
            "锅中少油，小火下白糖炒至焦糖色",
            "下肉块翻炒上色，加入姜片、葱段",
            "加料酒、生抽、老抽翻炒均匀",
            "加热水没过肉块，大火烧开转小火炖40分钟",
            "大火收汁至汤汁浓稠包裹肉块即可",
        ],
        "tags": ["经典", "硬菜", "多人食", "下饭"],
        "healthStars": 2, "dietFriendly": False, "dietNote": "高油高糖高热量，减肥期间不建议食用",
        "nutrition": {"calories": 650, "salt": 3.0, "protein": "高蛋白"},
    },
    {
        "id": "p005", "name": "糖醋里脊", "category": "猪肉类",
        "description": "外酥里嫩，酸甜可口，大人小孩都爱吃",
        "emoji": "🍖🍬", "prepTime": 15, "cookTime": 15,
        "ingredients": [
            {"name": "猪里脊", "amount": 300, "unit": "g"},
            {"name": "鸡蛋", "amount": 55, "unit": "g"},
        ],
        "seasonings": [
            {"name": "淀粉", "amount": 100, "unit": "g"},
            {"name": "白糖", "amount": 30, "unit": "g"},
            {"name": "醋", "amount": 30, "unit": "ml"},
            {"name": "番茄酱", "amount": 30, "unit": "g"},
            {"name": "生抽", "amount": 10, "unit": "ml"},
            {"name": "料酒", "amount": 10, "unit": "ml"},
            {"name": "食用油", "amount": 300, "unit": "ml"},
        ],
        "steps": [
            "里脊切条，加料酒、盐腌制10分钟",
            "调面糊：淀粉+鸡蛋+少量水搅成糊状",
            "里脊挂糊，油温七成热下锅炸至金黄捞出",
            "油温升高复炸30秒使其更酥脆",
            "另起锅：番茄酱+糖+醋+生抽+水煮开，勾芡",
            "倒入炸好的里脊快速翻匀，裹满酱汁出锅",
        ],
        "tags": ["经典", "下饭", "家常", "多人食"],
        "healthStars": 2, "dietFriendly": False, "dietNote": "油炸+高糖，热量极高，减肥期间禁止食用",
        "nutrition": {"calories": 580, "salt": 2.0, "protein": "高蛋白"},
    },
    {
        "id": "p006", "name": "肉末茄子", "category": "猪肉类",
        "description": "茄子吸满肉汁，软烂入味，拌饭一绝",
        "emoji": "🍆🥩", "prepTime": 10, "cookTime": 15,
        "ingredients": [
            {"name": "茄子", "amount": 500, "unit": "g"},
            {"name": "猪肉", "amount": 150, "unit": "g"},
            {"name": "大蒜", "amount": 15, "unit": "g"},
            {"name": "葱", "amount": 10, "unit": "g"},
        ],
        "seasonings": [
            {"name": "生抽", "amount": 15, "unit": "ml"},
            {"name": "老抽", "amount": 5, "unit": "ml"},
            {"name": "豆瓣酱", "amount": 10, "unit": "g"},
            {"name": "料酒", "amount": 10, "unit": "ml"},
            {"name": "白糖", "amount": 5, "unit": "g"},
            {"name": "食用油", "amount": 30, "unit": "ml"},
        ],
        "steps": [
            "茄子切条，用盐腌10分钟挤去水分（不油腻的关键）",
            "猪肉剁成肉末，加料酒生抽腌制",
            "蒜切末，葱切花",
            "锅中多油，下茄条煎至表面金黄盛出",
            "留底油下肉末炒散，加豆瓣酱和蒜末爆香",
            "倒回茄条，加生抽、老抽、白糖翻炒",
            "加少量水焖2分钟，收汁撒葱花出锅",
        ],
        "tags": ["下饭", "快手菜", "家常"],
        "healthStars": 3, "dietFriendly": False, "dietNote": "茄子吸油多，但可少油煎制降低热量",
        "nutrition": {"calories": 380, "salt": 2.8, "protein": "中蛋白"},
    },
    {
        "id": "p007", "name": "木须肉", "category": "猪肉类",
        "description": "肉蛋菜一锅出，营养均衡，快手家常菜",
        "emoji": "🥩🥒🥚", "prepTime": 10, "cookTime": 10,
        "ingredients": [
            {"name": "猪里脊", "amount": 150, "unit": "g"},
            {"name": "鸡蛋", "amount": 165, "unit": "g"},
            {"name": "黄瓜", "amount": 200, "unit": "g"},
            {"name": "木耳", "amount": 30, "unit": "g"},
        ],
        "seasonings": [
            {"name": "生抽", "amount": 15, "unit": "ml"},
            {"name": "料酒", "amount": 10, "unit": "ml"},
            {"name": "淀粉", "amount": 5, "unit": "g"},
            {"name": "食用油", "amount": 25, "unit": "ml"},
            {"name": "盐", "amount": 3, "unit": "g"},
        ],
        "steps": [
            "里脊切片，加料酒、生抽、淀粉腌制10分钟",
            "木耳泡发撕小朵，黄瓜切片，鸡蛋打散",
            "热油炒鸡蛋至凝固盛出",
            "锅中再加油，下肉片滑炒变色",
            "加木耳、黄瓜翻炒2分钟",
            "倒回鸡蛋，加盐翻匀出锅",
        ],
        "tags": ["快手菜", "营养均衡", "一人食"],
        "healthStars": 4, "dietFriendly": True, "dietNote": "荤素搭配，蛋白丰富，做法清淡适合减肥",
        "nutrition": {"calories": 260, "salt": 1.8, "protein": "高蛋白"},
    },
    {
        "id": "p008", "name": "蒜苔炒肉", "category": "猪肉类",
        "description": "简单快手的家常小炒，蒜苔口感清脆",
        "emoji": "🥩🌿", "prepTime": 10, "cookTime": 10,
        "ingredients": [
            {"name": "蒜苔", "amount": 200, "unit": "g"},
            {"name": "猪肉", "amount": 200, "unit": "g"},
            {"name": "大蒜", "amount": 10, "unit": "g"},
        ],
        "seasonings": [
            {"name": "生抽", "amount": 15, "unit": "ml"},
            {"name": "老抽", "amount": 5, "unit": "ml"},
            {"name": "料酒", "amount": 10, "unit": "ml"},
            {"name": "淀粉", "amount": 5, "unit": "g"},
            {"name": "盐", "amount": 2, "unit": "g"},
            {"name": "食用油", "amount": 20, "unit": "ml"},
        ],
        "steps": [
            "猪肉切丝或薄片，加料酒、生抽、淀粉腌制10分钟",
            "蒜苔洗净切段（约4cm长）",
            "热锅凉油，下肉片滑炒至变色盛出",
            "锅中留油，下蒜苔大火翻炒2分钟至表皮微皱",
            "倒回肉片，加生抽、老抽、盐翻匀即可",
        ],
        "tags": ["快手菜", "下饭", "家常"],
        "healthStars": 4, "dietFriendly": True, "dietNote": "瘦肉低脂，蒜苔纤维多，适合减肥期间食用",
        "nutrition": {"calories": 250, "salt": 2.0, "protein": "高蛋白"},
    },
    {
        "id": "p009", "name": "小炒肉", "category": "猪肉类",
        "description": "湖南经典下饭菜，香辣过瘾，能干掉三碗米饭",
        "emoji": "🌶️🥩", "prepTime": 10, "cookTime": 10,
        "ingredients": [
            {"name": "猪肉", "amount": 250, "unit": "g"},
            {"name": "青椒", "amount": 200, "unit": "g"},
            {"name": "大蒜", "amount": 15, "unit": "g"},
            {"name": "干辣椒", "amount": 10, "unit": "g"},
            {"name": "生姜", "amount": 10, "unit": "g"},
        ],
        "seasonings": [
            {"name": "生抽", "amount": 15, "unit": "ml"},
            {"name": "老抽", "amount": 5, "unit": "ml"},
            {"name": "料酒", "amount": 10, "unit": "ml"},
            {"name": "盐", "amount": 3, "unit": "g"},
            {"name": "食用油", "amount": 20, "unit": "ml"},
        ],
        "steps": [
            "猪肉切薄片，肥瘦分开",
            "青椒切块，姜蒜切片，干辣椒切段",
            "热锅少油，先下肥肉煸出油",
            "下瘦肉炒至变色，加姜蒜干辣椒爆香",
            "下青椒翻炒，加生抽、老抽、料酒",
            "大火快炒至青椒断生，盐调味出锅",
        ],
        "tags": ["下饭", "辣", "经典", "湖南菜"],
        "healthStars": 3, "dietFriendly": False, "dietNote": "偏油腻且辣，减肥期间适量食用",
        "nutrition": {"calories": 320, "salt": 2.6, "protein": "高蛋白"},
    },
    {
        "id": "p010", "name": "红烧排骨", "category": "猪肉类",
        "description": "软烂脱骨，酱香浓郁，宴客硬菜",
        "emoji": "🦴🍖", "prepTime": 10, "cookTime": 50,
        "ingredients": [
            {"name": "排骨", "amount": 500, "unit": "g"},
            {"name": "生姜", "amount": 15, "unit": "g"},
            {"name": "葱", "amount": 20, "unit": "g"},
            {"name": "土豆", "amount": 200, "unit": "g"},
        ],
        "seasonings": [
            {"name": "生抽", "amount": 25, "unit": "ml"},
            {"name": "老抽", "amount": 15, "unit": "ml"},
            {"name": "料酒", "amount": 20, "unit": "ml"},
            {"name": "白糖", "amount": 15, "unit": "g"},
            {"name": "醋", "amount": 10, "unit": "ml"},
            {"name": "食用油", "amount": 20, "unit": "ml"},
        ],
        "steps": [
            "排骨斩小块，冷水下锅焯水去浮沫，洗净沥干",
            "热锅少油下白糖，小火炒至焦糖色",
            "下排骨翻炒上色，加入姜片、葱段",
            "加料酒、生抽、老抽、醋炒匀",
            "加热水没过排骨，大火烧开转小火炖30分钟",
            "土豆去皮切块，加入锅中再炖15分钟",
            "大火收汁至浓稠即可",
        ],
        "tags": ["经典", "硬菜", "多人食", "下饭"],
        "healthStars": 3, "dietFriendly": False, "dietNote": "油脂和糖分较高，减肥期间建议少吃",
        "nutrition": {"calories": 500, "salt": 3.5, "protein": "高蛋白"},
    },
    {
        "id": "p012", "name": "粉蒸肉", "category": "猪肉类",
        "description": "肉香米香交融，入口即化，老少皆宜",
        "emoji": "🥓🍚", "prepTime": 20, "cookTime": 60,
        "ingredients": [
            {"name": "五花肉", "amount": 400, "unit": "g"},
            {"name": "土豆", "amount": 200, "unit": "g"},
            {"name": "生姜", "amount": 10, "unit": "g"},
            {"name": "葱", "amount": 10, "unit": "g"},
        ],
        "seasonings": [
            {"name": "生抽", "amount": 20, "unit": "ml"},
            {"name": "老抽", "amount": 10, "unit": "ml"},
            {"name": "料酒", "amount": 15, "unit": "ml"},
            {"name": "豆瓣酱", "amount": 15, "unit": "g"},
            {"name": "白糖", "amount": 5, "unit": "g"},
        ],
        "steps": [
            "五花肉切厚片，加所有调料和姜末腌制30分钟",
            "腌好的肉裹上蒸肉米粉（可买现成的）",
            "土豆去皮切块铺在碗底",
            "将裹好米粉的肉铺在土豆上面",
            "上蒸锅大火蒸60分钟至肉软烂",
            "出锅撒葱花即可",
        ],
        "tags": ["经典", "蒸菜", "多人食"],
        "healthStars": 3, "dietFriendly": False, "dietNote": "蒸制做法比红烧健康些，但五花肉脂肪仍高",
        "nutrition": {"calories": 480, "salt": 2.8, "protein": "高蛋白"},
    },

    # ============================
    # 鸡肉类（约 12 道）
    # ============================
    {
        "id": "c005", "name": "可乐鸡翅", "category": "鸡肉类",
        "description": "咸甜可口，色泽红亮，新手零失败硬菜",
        "emoji": "🍗🥤", "prepTime": 5, "cookTime": 25,
        "ingredients": [
            {"name": "鸡翅", "amount": 500, "unit": "g"},
            {"name": "生姜", "amount": 10, "unit": "g"},
        ],
        "seasonings": [
            {"name": "生抽", "amount": 15, "unit": "ml"},
            {"name": "老抽", "amount": 10, "unit": "ml"},
            {"name": "料酒", "amount": 15, "unit": "ml"},
            {"name": "食用油", "amount": 15, "unit": "ml"},
        ],
        "steps": [
            "鸡翅洗净，两面各划两刀方便入味",
            "冷水下锅焯水去浮沫，捞出洗净",
            "热锅少油，下鸡翅煎至两面金黄",
            "加姜片、料酒、生抽、老抽翻炒",
            "倒入可乐刚好没过鸡翅",
            "大火烧开转中小火煮15分钟",
            "大火收汁至浓稠包裹鸡翅即可",
        ],
        "tags": ["快手菜", "下饭", "家常", "新手友好"],
        "healthStars": 3, "dietFriendly": False, "dietNote": "可乐含糖高，鸡翅皮脂肪多，减肥期间建议去皮",
        "nutrition": {"calories": 400, "salt": 2.5, "protein": "高蛋白"},
    },
    {
        "id": "c006", "name": "辣子鸡", "category": "鸡肉类",
        "description": "干香麻辣，越嚼越香，在辣椒里找鸡丁的快乐",
        "emoji": "🌶️🍗", "prepTime": 15, "cookTime": 15,
        "ingredients": [
            {"name": "鸡腿", "amount": 600, "unit": "g"},
            {"name": "干辣椒", "amount": 30, "unit": "g"},
            {"name": "花椒", "amount": 10, "unit": "g"},
            {"name": "生姜", "amount": 10, "unit": "g"},
            {"name": "大蒜", "amount": 15, "unit": "g"},
            {"name": "葱", "amount": 15, "unit": "g"},
        ],
        "seasonings": [
            {"name": "生抽", "amount": 15, "unit": "ml"},
            {"name": "料酒", "amount": 15, "unit": "ml"},
            {"name": "淀粉", "amount": 10, "unit": "g"},
            {"name": "白糖", "amount": 5, "unit": "g"},
            {"name": "食用油", "amount": 300, "unit": "ml"},
            {"name": "盐", "amount": 3, "unit": "g"},
        ],
        "steps": [
            "鸡腿去骨切丁，加料酒、生抽、淀粉腌15分钟",
            "干辣椒剪段，姜蒜切片",
            "油温七成热，下鸡丁炸至金黄捞出",
            "油温升高复炸至酥脆",
            "锅中留底油，小火炒香干辣椒和花椒",
            "下姜蒜片爆香",
            "倒入鸡丁，加白糖、盐翻炒均匀",
            "撒葱段、白芝麻出锅",
        ],
        "tags": ["辣", "经典", "川菜", "下饭"],
        "healthStars": 2, "dietFriendly": False, "dietNote": "油炸+麻辣，高热量，减肥期间不建议食用",
        "nutrition": {"calories": 480, "salt": 3.5, "protein": "高蛋白"},
    },
    {
        "id": "c007", "name": "蒜香鸡胸肉", "category": "鸡肉类",
        "description": "简单快手的减脂餐，蒜香浓郁，嫩而不柴",
        "emoji": "🍗🧄", "prepTime": 15, "cookTime": 10,
        "ingredients": [
            {"name": "鸡胸肉", "amount": 300, "unit": "g"},
            {"name": "大蒜", "amount": 20, "unit": "g"},
            {"name": "西兰花", "amount": 200, "unit": "g"},
        ],
        "seasonings": [
            {"name": "生抽", "amount": 15, "unit": "ml"},
            {"name": "料酒", "amount": 10, "unit": "ml"},
            {"name": "淀粉", "amount": 5, "unit": "g"},
            {"name": "食用油", "amount": 15, "unit": "ml"},
            {"name": "盐", "amount": 2, "unit": "g"},
        ],
        "steps": [
            "鸡胸肉片成薄片，加料酒、生抽、淀粉腌15分钟",
            "大蒜切末（越多越香），西兰花掰小朵焯水",
            "热锅少油，下鸡胸肉片中火煎至两面金黄",
            "下蒜末炒香，淋少许生抽",
            "搭配焯好的西兰花装盘",
        ],
        "tags": ["快手菜", "减脂", "一人食", "清淡"],
        "healthStars": 5, "dietFriendly": True, "dietNote": "低脂高蛋白，西兰花低热量，完美减脂餐",
        "nutrition": {"calories": 220, "salt": 1.5, "protein": "高蛋白"},
    },
    {
        "id": "c008", "name": "咖喱鸡", "category": "鸡肉类",
        "description": "浓郁咖喱香，土豆绵软，拌饭拌面都好吃",
        "emoji": "🍗🍛", "prepTime": 10, "cookTime": 25,
        "ingredients": [
            {"name": "鸡腿", "amount": 600, "unit": "g"},
            {"name": "土豆", "amount": 400, "unit": "g"},
            {"name": "胡萝卜", "amount": 100, "unit": "g"},
            {"name": "洋葱", "amount": 200, "unit": "g"},
        ],
        "seasonings": [
            {"name": "料酒", "amount": 10, "unit": "ml"},
            {"name": "食用油", "amount": 20, "unit": "ml"},
            {"name": "盐", "amount": 2, "unit": "g"},
        ],
        "steps": [
            "鸡腿剁块焯水，土豆胡萝卜去皮切块，洋葱切块",
            "热锅加油，下洋葱炒至透明出香",
            "下鸡块翻炒至表面微黄",
            "加土豆块、胡萝卜块翻炒",
            "放入咖喱块（约50g），加水没过食材",
            "大火烧开转中小火煮20分钟至土豆软烂",
            "汤汁浓稠时加盐调味即可",
        ],
        "tags": ["下饭", "家常", "多人食"],
        "healthStars": 3, "dietFriendly": False, "dietNote": "咖喱块含油较高，但鸡肉和蔬菜搭配好",
        "nutrition": {"calories": 380, "salt": 2.5, "protein": "高蛋白"},
    },
    {
        "id": "c009", "name": "葱油鸡", "category": "鸡肉类",
        "description": "葱香四溢，鸡肉嫩滑，不放一滴水的美味",
        "emoji": "🍗🧅", "prepTime": 10, "cookTime": 25,
        "ingredients": [
            {"name": "鸡腿", "amount": 600, "unit": "g"},
            {"name": "葱", "amount": 50, "unit": "g"},
            {"name": "生姜", "amount": 20, "unit": "g"},
        ],
        "seasonings": [
            {"name": "生抽", "amount": 15, "unit": "ml"},
            {"name": "料酒", "amount": 15, "unit": "ml"},
            {"name": "食用油", "amount": 30, "unit": "ml"},
            {"name": "盐", "amount": 3, "unit": "g"},
        ],
        "steps": [
            "鸡腿洗净，表面抹盐和料酒腌制15分钟",
            "姜一半切片一半切末，葱切段和葱花",
            "锅底铺满葱段和姜片",
            "鸡腿放在葱姜上，加盖小火焗20分钟",
            "另起锅烧热油，炸香葱末和姜末",
            "焗好的鸡腿撕成块，淋上葱油和生抽即可",
        ],
        "tags": ["家常", "下饭", "经典"],
        "healthStars": 4, "dietFriendly": True, "dietNote": "焗制少油，鸡肉低脂，适合减肥期间食用",
        "nutrition": {"calories": 280, "salt": 2.0, "protein": "高蛋白"},
    },
    {
        "id": "c010", "name": "香菇滑鸡", "category": "鸡肉类",
        "description": "蒸出来的鲜美，鸡肉嫩滑，香菇入味",
        "emoji": "🍗🍄", "prepTime": 15, "cookTime": 20,
        "ingredients": [
            {"name": "鸡腿", "amount": 450, "unit": "g"},
            {"name": "蘑菇", "amount": 100, "unit": "g"},
            {"name": "生姜", "amount": 10, "unit": "g"},
            {"name": "葱", "amount": 10, "unit": "g"},
        ],
        "seasonings": [
            {"name": "生抽", "amount": 15, "unit": "ml"},
            {"name": "老抽", "amount": 5, "unit": "ml"},
            {"name": "料酒", "amount": 10, "unit": "ml"},
            {"name": "淀粉", "amount": 10, "unit": "g"},
            {"name": "蚝油", "amount": 10, "unit": "ml"},
            {"name": "白糖", "amount": 3, "unit": "g"},
            {"name": "食用油", "amount": 15, "unit": "ml"},
        ],
        "steps": [
            "鸡腿去骨切块，加所有调料和姜丝腌制20分钟",
            "香菇洗净切片，铺在盘底",
            "腌好的鸡块铺在香菇上面",
            "上蒸锅大火蒸15-20分钟",
            "出锅撒葱花即可",
        ],
        "tags": ["蒸菜", "快手菜", "健康", "家常"],
        "healthStars": 5, "dietFriendly": True, "dietNote": "蒸制做法几乎无油，低脂高蛋白，非常适合减肥",
        "nutrition": {"calories": 230, "salt": 2.0, "protein": "高蛋白"},
    },
    {
        "id": "c011", "name": "鸡肉炖蘑菇", "category": "鸡肉类",
        "description": "东北经典炖菜，汤鲜肉香，暖胃暖心",
        "emoji": "🍗🍄", "prepTime": 15, "cookTime": 45,
        "ingredients": [
            {"name": "鸡腿", "amount": 600, "unit": "g"},
            {"name": "蘑菇", "amount": 200, "unit": "g"},
            {"name": "土豆", "amount": 200, "unit": "g"},
            {"name": "生姜", "amount": 10, "unit": "g"},
            {"name": "葱", "amount": 15, "unit": "g"},
        ],
        "seasonings": [
            {"name": "生抽", "amount": 20, "unit": "ml"},
            {"name": "老抽", "amount": 5, "unit": "ml"},
            {"name": "料酒", "amount": 15, "unit": "ml"},
            {"name": "食用油", "amount": 15, "unit": "ml"},
            {"name": "盐", "amount": 4, "unit": "g"},
        ],
        "steps": [
            "鸡腿剁块，冷水焯水洗净",
            "蘑菇洗净，土豆去皮切块",
            "热锅加油，爆香姜片和葱段",
            "下鸡块翻炒至微黄，加料酒生抽老抽",
            "加水大火烧开，放入蘑菇",
            "转小火炖30分钟",
            "加土豆再炖15分钟，盐调味出锅",
        ],
        "tags": ["炖菜", "家常", "东北菜", "汤"],
        "healthStars": 4, "dietFriendly": True, "dietNote": "炖制做法温和，蘑菇低热量，营养均衡",
        "nutrition": {"calories": 300, "salt": 2.8, "protein": "高蛋白"},
    },
    {
        "id": "c012", "name": "盐焗鸡", "category": "鸡肉类",
        "description": "原汁原味，咸香入味，做法超简单",
        "emoji": "🍗🧂", "prepTime": 10, "cookTime": 30,
        "ingredients": [
            {"name": "鸡腿", "amount": 600, "unit": "g"},
            {"name": "生姜", "amount": 20, "unit": "g"},
            {"name": "葱", "amount": 20, "unit": "g"},
        ],
        "seasonings": [
            {"name": "料酒", "amount": 15, "unit": "ml"},
            {"name": "食用油", "amount": 15, "unit": "ml"},
            {"name": "盐", "amount": 10, "unit": "g"},
        ],
        "steps": [
            "鸡腿洗净，用厨房纸吸干水分",
            "正反面均匀抹盐，加料酒腌制20分钟",
            "电饭煲底铺姜片和葱段",
            "放入鸡腿，淋少许油",
            "按下煮饭键，跳闸后再焖10分钟",
            "取出撕成条即可食用",
        ],
        "tags": ["快手菜", "电饭煲", "新手友好", "家常"],
        "healthStars": 4, "dietFriendly": True, "dietNote": "做法简单少油，鸡腿去皮后非常适合减肥",
        "nutrition": {"calories": 250, "salt": 3.0, "protein": "高蛋白"},
    },

    # ============================
    # 鸡蛋类（约 10 道）
    # ============================
    {
        "id": "e001", "name": "番茄炒蛋", "category": "鸡蛋类",
        "description": "国民第一家常菜，酸甜开胃，百吃不厌",
        "emoji": "🍅🥚", "prepTime": 5, "cookTime": 10,
        "ingredients": [
            {"name": "鸡蛋", "amount": 165, "unit": "g"},
            {"name": "番茄", "amount": 300, "unit": "g"},
            {"name": "葱", "amount": 10, "unit": "g"},
        ],
        "seasonings": [
            {"name": "白糖", "amount": 5, "unit": "g"},
            {"name": "食用油", "amount": 25, "unit": "ml"},
            {"name": "盐", "amount": 3, "unit": "g"},
        ],
        "steps": [
            "鸡蛋打散加少许盐搅匀，番茄切块，葱切花",
            "热锅多油，下蛋液炒至凝固蓬松盛出",
            "锅中留油，下番茄块中火炒至出汁变软",
            "加白糖提鲜去酸",
            "倒回鸡蛋，翻炒均匀，加盐调味",
            "撒葱花出锅",
        ],
        "tags": ["快手菜", "经典", "下饭", "新手友好", "一人食"],
        "healthStars": 4, "dietFriendly": True, "dietNote": "低热量家常菜，番茄抗氧化，鸡蛋优质蛋白",
        "nutrition": {"calories": 220, "salt": 1.8, "protein": "中蛋白"},
    },
    {
        "id": "e002", "name": "青椒炒蛋", "category": "鸡蛋类",
        "description": "简单快手，三分钟出锅，懒人必备",
        "emoji": "🫑🥚", "prepTime": 5, "cookTime": 5,
        "ingredients": [
            {"name": "鸡蛋", "amount": 165, "unit": "g"},
            {"name": "青椒", "amount": 200, "unit": "g"},
        ],
        "seasonings": [
            {"name": "生抽", "amount": 10, "unit": "ml"},
            {"name": "食用油", "amount": 20, "unit": "ml"},
            {"name": "盐", "amount": 2, "unit": "g"},
        ],
        "steps": [
            "鸡蛋打散加少许盐搅匀",
            "青椒去籽切丝或小块",
            "热锅加油，下蛋液炒至凝固盛出",
            "锅中加少许油，下青椒翻炒1分钟",
            "倒回鸡蛋，加生抽和盐翻匀即可",
        ],
        "tags": ["快手菜", "一人食", "下饭", "新手友好"],
        "healthStars": 5, "dietFriendly": True, "dietNote": "低脂低热量，青椒维C丰富，减肥期间推荐",
        "nutrition": {"calories": 180, "salt": 1.5, "protein": "中蛋白"},
    },
    {
        "id": "e003", "name": "韭菜炒蛋", "category": "鸡蛋类",
        "description": "春天的味道，韭菜鲜香，简单快手",
        "emoji": "🌿🥚", "prepTime": 5, "cookTime": 5,
        "ingredients": [
            {"name": "鸡蛋", "amount": 165, "unit": "g"},
            {"name": "韭菜", "amount": 200, "unit": "g"},
        ],
        "seasonings": [
            {"name": "食用油", "amount": 20, "unit": "ml"},
            {"name": "盐", "amount": 2, "unit": "g"},
        ],
        "steps": [
            "韭菜洗净切段，鸡蛋打散加盐搅匀",
            "热锅加油，先炒鸡蛋至凝固盛出",
            "锅中加少许油，大火下韭菜快炒30秒",
            "倒回鸡蛋，快速翻匀，韭菜变软马上出锅",
        ],
        "tags": ["快手菜", "一人食", "家常", "春季"],
        "healthStars": 5, "dietFriendly": True, "dietNote": "低热量高纤维，韭菜助消化，非常健康",
        "nutrition": {"calories": 170, "salt": 1.3, "protein": "中蛋白"},
    },
    {
        "id": "e004", "name": "洋葱炒蛋", "category": "鸡蛋类",
        "description": "洋葱甜香配嫩滑鸡蛋，简单又营养",
        "emoji": "🧅🥚", "prepTime": 5, "cookTime": 5,
        "ingredients": [
            {"name": "鸡蛋", "amount": 165, "unit": "g"},
            {"name": "洋葱", "amount": 200, "unit": "g"},
        ],
        "seasonings": [
            {"name": "生抽", "amount": 10, "unit": "ml"},
            {"name": "食用油", "amount": 20, "unit": "ml"},
            {"name": "盐", "amount": 2, "unit": "g"},
        ],
        "steps": [
            "鸡蛋打散加盐搅匀，洋葱切丝",
            "热锅加油，先炒鸡蛋盛出",
            "锅中下洋葱丝炒至透明变软出香",
            "倒回鸡蛋，加生抽翻匀即可",
        ],
        "tags": ["快手菜", "一人食", "下饭"],
        "healthStars": 4, "dietFriendly": True, "dietNote": "洋葱降血脂，鸡蛋优质蛋白，健康家常菜",
        "nutrition": {"calories": 190, "salt": 1.5, "protein": "中蛋白"},
    },
    {
        "id": "e005", "name": "蒸蛋羹", "category": "鸡蛋类",
        "description": "嫩滑如布丁，入口即化，老少皆宜",
        "emoji": "🥚🍮", "prepTime": 5, "cookTime": 12,
        "ingredients": [
            {"name": "鸡蛋", "amount": 110, "unit": "g"},
            {"name": "葱", "amount": 5, "unit": "g"},
        ],
        "seasonings": [
            {"name": "生抽", "amount": 5, "unit": "ml"},
            {"name": "食用油", "amount": 5, "unit": "ml"},
            {"name": "盐", "amount": 1, "unit": "g"},
        ],
        "steps": [
            "鸡蛋打散，加1.5倍温水（约150ml）和盐搅匀",
            "用滤网过滤掉泡沫（嫩滑的关键）",
            "碗上盖保鲜膜，扎几个小孔",
            "水开后上锅，中小火蒸10-12分钟",
            "出锅淋上生抽和少许热油，撒葱花",
        ],
        "tags": ["快手菜", "健康", "清淡", "一人食"],
        "healthStars": 5, "dietFriendly": True, "dietNote": "低脂高蛋白，蒸制无油，减肥期间非常适合",
        "nutrition": {"calories": 120, "salt": 1.0, "protein": "高蛋白"},
    },
    {
        "id": "e006", "name": "蛋花汤", "category": "鸡蛋类",
        "description": "一碗热汤配饭正好，蛋花飘香，清爽解腻",
        "emoji": "🥚🍲", "prepTime": 3, "cookTime": 5,
        "ingredients": [
            {"name": "鸡蛋", "amount": 110, "unit": "g"},
            {"name": "番茄", "amount": 150, "unit": "g"},
            {"name": "葱", "amount": 5, "unit": "g"},
        ],
        "seasonings": [
            {"name": "食用油", "amount": 5, "unit": "ml"},
            {"name": "盐", "amount": 2, "unit": "g"},
        ],
        "steps": [
            "番茄切块，鸡蛋打散备用",
            "锅中少油炒番茄至出汁",
            "加水烧开煮2分钟",
            "转小火，绕圈淋入蛋液，不要搅动",
            "等蛋花浮起，加盐调味，撒葱花出锅",
        ],
        "tags": ["快手菜", "汤", "清爽", "一人食"],
        "healthStars": 5, "dietFriendly": True, "dietNote": "低脂低热量，清爽解腻，减肥友好",
        "nutrition": {"calories": 100, "salt": 1.2, "protein": "中蛋白"},
    },
    {
        "id": "e007", "name": "苦瓜炒蛋", "category": "鸡蛋类",
        "description": "清热去火，夏天必备，苦中有香",
        "emoji": "🥒🥚", "prepTime": 5, "cookTime": 5,
        "ingredients": [
            {"name": "鸡蛋", "amount": 165, "unit": "g"},
            {"name": "苦瓜", "amount": 200, "unit": "g"},
        ],
        "seasonings": [
            {"name": "食用油", "amount": 20, "unit": "ml"},
            {"name": "盐", "amount": 2, "unit": "g"},
        ],
        "steps": [
            "苦瓜对半切开，去瓤去白膜（白膜越干净越不苦）",
            "切薄片，加盐腌制10分钟后挤去苦水",
            "鸡蛋打散加少许盐搅匀",
            "热锅加油，下苦瓜翻炒1分钟",
            "倒入蛋液，待底部凝固后翻炒",
            "炒至蛋熟即可出锅",
        ],
        "tags": ["快手菜", "健康", "下火", "夏季"],
        "healthStars": 5, "dietFriendly": True, "dietNote": "低热量高纤维，清热去火，减肥期间推荐",
        "nutrition": {"calories": 160, "salt": 1.5, "protein": "中蛋白"},
    },
    {
        "id": "e008", "name": "虾仁滑蛋", "category": "鸡蛋类",
        "description": "蛋嫩虾鲜，丝滑口感，港式茶餐厅经典",
        "emoji": "🦐🥚", "prepTime": 10, "cookTime": 5,
        "ingredients": [
            {"name": "鸡蛋", "amount": 165, "unit": "g"},
            {"name": "虾仁", "amount": 150, "unit": "g"},
            {"name": "葱", "amount": 5, "unit": "g"},
        ],
        "seasonings": [
            {"name": "料酒", "amount": 5, "unit": "ml"},
            {"name": "淀粉", "amount": 3, "unit": "g"},
            {"name": "食用油", "amount": 20, "unit": "ml"},
            {"name": "盐", "amount": 2, "unit": "g"},
        ],
        "steps": [
            "虾仁加料酒、少许盐、淀粉抓匀腌制10分钟",
            "鸡蛋打散加少许盐搅匀",
            "热锅加油，下虾仁滑炒至变红盛出",
            "虾仁稍凉后倒入蛋液中搅匀",
            "锅中再加油，倒入虾仁蛋液",
            "小火慢慢推炒至蛋液凝固即可，不要炒老",
        ],
        "tags": ["快手菜", "下饭", "营养", "港式"],
        "healthStars": 4, "dietFriendly": True, "dietNote": "高蛋白低脂，虾仁低热量，适合减脂增肌",
        "nutrition": {"calories": 240, "salt": 1.8, "protein": "高蛋白"},
    },
    {
        "id": "e009", "name": "蛋炒饭", "category": "鸡蛋类",
        "description": "隔夜饭的终极归宿，粒粒分明，香气扑鼻",
        "emoji": "🍚🥚", "prepTime": 5, "cookTime": 10,
        "ingredients": [
            {"name": "鸡蛋", "amount": 110, "unit": "g"},
            {"name": "大米", "amount": 200, "unit": "g"},
            {"name": "葱", "amount": 10, "unit": "g"},
            {"name": "火腿肠", "amount": 50, "unit": "g"},
        ],
        "seasonings": [
            {"name": "生抽", "amount": 10, "unit": "ml"},
            {"name": "食用油", "amount": 25, "unit": "ml"},
            {"name": "盐", "amount": 2, "unit": "g"},
        ],
        "steps": [
            "米饭提前煮好放凉（隔夜饭最佳）",
            "鸡蛋打散，火腿肠切丁，葱切花",
            "热锅多油，下蛋液快速炒散盛出",
            "锅中加油，下米饭大火翻炒打散",
            "加火腿丁翻炒",
            "倒回鸡蛋，加生抽和盐，大火翻炒均匀",
            "撒葱花出锅",
        ],
        "tags": ["快手菜", "主食", "一人食", "经典"],
        "healthStars": 3, "dietFriendly": False, "dietNote": "炒饭油多碳水高，减肥期间适量食用",
        "nutrition": {"calories": 450, "salt": 2.5, "protein": "中蛋白"},
    },

    # ============================
    # 牛肉类（约 8 道）
    # ============================
    {
        "id": "b001", "name": "青椒牛柳", "category": "牛肉类",
        "description": "牛肉滑嫩，青椒脆爽，下饭好菜",
        "emoji": "🫑🥩", "prepTime": 15, "cookTime": 10,
        "ingredients": [
            {"name": "牛肉", "amount": 250, "unit": "g"},
            {"name": "青椒", "amount": 200, "unit": "g"},
            {"name": "生姜", "amount": 10, "unit": "g"},
            {"name": "大蒜", "amount": 10, "unit": "g"},
        ],
        "seasonings": [
            {"name": "生抽", "amount": 15, "unit": "ml"},
            {"name": "老抽", "amount": 5, "unit": "ml"},
            {"name": "料酒", "amount": 10, "unit": "ml"},
            {"name": "淀粉", "amount": 10, "unit": "g"},
            {"name": "蚝油", "amount": 10, "unit": "ml"},
            {"name": "食用油", "amount": 25, "unit": "ml"},
            {"name": "盐", "amount": 2, "unit": "g"},
        ],
        "steps": [
            "牛肉逆纹切条，加料酒、生抽、淀粉、少许油腌制15分钟",
            "青椒切条，姜蒜切片",
            "热锅凉油，油温六成下牛肉滑炒至变色立刻盛出",
            "锅中留油，爆香姜蒜",
            "下青椒翻炒至断生",
            "倒回牛肉，加生抽、老抽、蚝油、盐快炒翻匀",
        ],
        "tags": ["下饭", "快手菜", "经典"],
        "healthStars": 4, "dietFriendly": True, "dietNote": "牛肉低脂高蛋白，青椒维C丰富，适合健身人群",
        "nutrition": {"calories": 260, "salt": 2.0, "protein": "高蛋白"},
    },
    {
        "id": "b002", "name": "红烧牛肉", "category": "牛肉类",
        "description": "软烂入味，汤汁浓郁，可以当面条浇头",
        "emoji": "🥩🍖", "prepTime": 10, "cookTime": 90,
        "ingredients": [
            {"name": "牛肉", "amount": 500, "unit": "g"},
            {"name": "土豆", "amount": 400, "unit": "g"},
            {"name": "胡萝卜", "amount": 100, "unit": "g"},
            {"name": "洋葱", "amount": 200, "unit": "g"},
            {"name": "生姜", "amount": 15, "unit": "g"},
            {"name": "葱", "amount": 15, "unit": "g"},
        ],
        "seasonings": [
            {"name": "生抽", "amount": 25, "unit": "ml"},
            {"name": "老抽", "amount": 15, "unit": "ml"},
            {"name": "料酒", "amount": 20, "unit": "ml"},
            {"name": "豆瓣酱", "amount": 15, "unit": "g"},
            {"name": "白糖", "amount": 10, "unit": "g"},
            {"name": "食用油", "amount": 25, "unit": "ml"},
        ],
        "steps": [
            "牛肉切块，冷水下锅焯水去浮沫，温水洗净",
            "土豆胡萝卜去皮切块，洋葱切块",
            "热锅加油，下白糖炒至焦糖色",
            "下牛肉块翻炒上色，加姜片葱段",
            "加豆瓣酱、料酒、生抽、老抽炒匀",
            "加热水没过牛肉，大火烧开转小火炖60分钟",
            "加土豆胡萝卜洋葱继续炖20分钟",
            "大火收汁至汤汁浓稠",
        ],
        "tags": ["硬菜", "经典", "下饭", "多人食"],
        "healthStars": 3, "dietFriendly": False, "dietNote": "红烧做法油糖偏多，但牛肉本身低脂",
        "nutrition": {"calories": 460, "salt": 3.5, "protein": "高蛋白"},
    },
    {
        "id": "b003", "name": "番茄牛腩", "category": "牛肉类",
        "description": "酸甜浓郁，牛腩软烂，汤汁拌饭一绝",
        "emoji": "🍅🥩", "prepTime": 10, "cookTime": 80,
        "ingredients": [
            {"name": "牛腩", "amount": 500, "unit": "g"},
            {"name": "番茄", "amount": 450, "unit": "g"},
            {"name": "土豆", "amount": 200, "unit": "g"},
            {"name": "洋葱", "amount": 200, "unit": "g"},
            {"name": "生姜", "amount": 15, "unit": "g"},
        ],
        "seasonings": [
            {"name": "生抽", "amount": 15, "unit": "ml"},
            {"name": "料酒", "amount": 20, "unit": "ml"},
            {"name": "白糖", "amount": 10, "unit": "g"},
            {"name": "食用油", "amount": 20, "unit": "ml"},
            {"name": "盐", "amount": 3, "unit": "g"},
        ],
        "steps": [
            "牛腩切块，冷水焯水洗净",
            "番茄一半切块一半切碎，土豆切块，洋葱切块",
            "热锅加油，下洋葱炒香",
            "下番茄碎炒出红油（可用番茄酱辅助）",
            "下牛腩块翻炒，加姜片、料酒、生抽",
            "加热水没过食材，大火烧开转小火炖60分钟",
            "加土豆块和剩余番茄块，继续炖15分钟",
            "加盐和白糖调味即可",
        ],
        "tags": ["经典", "汤", "下饭", "多人食"],
        "healthStars": 4, "dietFriendly": True, "dietNote": "番茄低热量，牛腩虽含脂肪但炖制后大部分融入汤中",
        "nutrition": {"calories": 350, "salt": 2.5, "protein": "高蛋白"},
    },
    {
        "id": "b004", "name": "水煮牛肉", "category": "牛肉类",
        "description": "麻辣鲜香，牛肉嫩滑，川菜经典大菜",
        "emoji": "🌶️🥩", "prepTime": 15, "cookTime": 15,
        "ingredients": [
            {"name": "牛肉", "amount": 300, "unit": "g"},
            {"name": "生菜", "amount": 200, "unit": "g"},
            {"name": "大蒜", "amount": 15, "unit": "g"},
            {"name": "生姜", "amount": 10, "unit": "g"},
            {"name": "干辣椒", "amount": 20, "unit": "g"},
            {"name": "花椒", "amount": 10, "unit": "g"},
        ],
        "seasonings": [
            {"name": "豆瓣酱", "amount": 25, "unit": "g"},
            {"name": "生抽", "amount": 10, "unit": "ml"},
            {"name": "料酒", "amount": 15, "unit": "ml"},
            {"name": "淀粉", "amount": 10, "unit": "g"},
            {"name": "食用油", "amount": 40, "unit": "ml"},
            {"name": "盐", "amount": 2, "unit": "g"},
        ],
        "steps": [
            "牛肉逆纹切薄片，加料酒、生抽、淀粉腌制15分钟",
            "生菜洗净铺在大碗底",
            "姜蒜切末，干辣椒剪段",
            "热锅加油，下豆瓣酱炒出红油",
            "加姜蒜末爆香，加水烧开",
            "转小火，一片片下入牛肉片，煮至变色（约1分钟）",
            "连汤带肉倒在生菜上",
            "牛肉上撒蒜末、干辣椒段、花椒",
            "另起锅烧热油，淋在辣椒上激出香味",
        ],
        "tags": ["辣", "经典", "川菜", "硬菜"],
        "healthStars": 3, "dietFriendly": False, "dietNote": "油较多且辣，减肥期间少油少辣可改良",
        "nutrition": {"calories": 380, "salt": 3.0, "protein": "高蛋白"},
    },
    {
        "id": "b005", "name": "土豆烧牛肉", "category": "牛肉类",
        "description": "经典搭配，块大肉香，豪爽的家常硬菜",
        "emoji": "🥔🥩", "prepTime": 10, "cookTime": 70,
        "ingredients": [
            {"name": "牛肉", "amount": 400, "unit": "g"},
            {"name": "土豆", "amount": 400, "unit": "g"},
            {"name": "胡萝卜", "amount": 100, "unit": "g"},
            {"name": "生姜", "amount": 10, "unit": "g"},
            {"name": "葱", "amount": 15, "unit": "g"},
        ],
        "seasonings": [
            {"name": "生抽", "amount": 20, "unit": "ml"},
            {"name": "老抽", "amount": 10, "unit": "ml"},
            {"name": "料酒", "amount": 15, "unit": "ml"},
            {"name": "豆瓣酱", "amount": 10, "unit": "g"},
            {"name": "白糖", "amount": 5, "unit": "g"},
            {"name": "食用油", "amount": 20, "unit": "ml"},
        ],
        "steps": [
            "牛肉切块焯水，土豆胡萝卜去皮切滚刀块",
            "热锅加油，爆香姜片葱段",
            "下牛肉块翻炒，加豆瓣酱炒出红油",
            "加料酒、生抽、老抽、白糖炒匀",
            "加热水没过牛肉，大火烧开转小火炖50分钟",
            "加土豆胡萝卜再炖20分钟",
            "大火收汁出锅",
        ],
        "tags": ["经典", "硬菜", "下饭", "家常"],
        "healthStars": 3, "dietFriendly": True, "dietNote": "牛肉瘦，土豆提供碳水，一锅搞定主食配菜",
        "nutrition": {"calories": 380, "salt": 2.5, "protein": "高蛋白"},
    },
    {
        "id": "b006", "name": "孜然牛肉", "category": "牛肉类",
        "description": "烧烤风味，孜然飘香，下酒下饭皆宜",
        "emoji": "🥩🧂", "prepTime": 15, "cookTime": 8,
        "ingredients": [
            {"name": "牛肉", "amount": 300, "unit": "g"},
            {"name": "洋葱", "amount": 200, "unit": "g"},
            {"name": "干辣椒", "amount": 5, "unit": "g"},
        ],
        "seasonings": [
            {"name": "生抽", "amount": 15, "unit": "ml"},
            {"name": "料酒", "amount": 10, "unit": "ml"},
            {"name": "淀粉", "amount": 5, "unit": "g"},
            {"name": "食用油", "amount": 25, "unit": "ml"},
            {"name": "盐", "amount": 3, "unit": "g"},
        ],
        "steps": [
            "牛肉切薄片，加料酒、生抽、淀粉腌15分钟",
            "洋葱切丝",
            "热锅多油，大火下牛肉片快速滑炒至变色盛出",
            "锅中留油，下洋葱丝和干辣椒炒香",
            "倒回牛肉，撒入孜然粉和辣椒粉",
            "大火快炒翻匀，加盐调味出锅",
        ],
        "tags": ["下饭", "快手菜", "烧烤风"],
        "healthStars": 4, "dietFriendly": True, "dietNote": "牛肉瘦，少油大火快炒，适合健身增肌",
        "nutrition": {"calories": 280, "salt": 2.0, "protein": "高蛋白"},
    },
    {
        "id": "b007", "name": "蒜香牛排", "category": "牛肉类",
        "description": "简单快手的西式做法，黄油蒜香，肉汁丰富",
        "emoji": "🥩🧄", "prepTime": 5, "cookTime": 10,
        "ingredients": [
            {"name": "牛肉", "amount": 300, "unit": "g"},
            {"name": "大蒜", "amount": 15, "unit": "g"},
        ],
        "seasonings": [
            {"name": "生抽", "amount": 10, "unit": "ml"},
            {"name": "料酒", "amount": 10, "unit": "ml"},
            {"name": "食用油", "amount": 20, "unit": "ml"},
            {"name": "盐", "amount": 3, "unit": "g"},
        ],
        "steps": [
            "牛肉切成1.5cm厚片，用厨房纸吸干水分",
            "两面撒盐和黑胡椒腌制5分钟",
            "蒜切片",
            "热锅热油，下牛排中大火每面煎2-3分钟",
            "加入蒜片和黄油（如有），用勺子浇油在牛排上",
            "煎好后静置3分钟再切片食用",
        ],
        "tags": ["快手菜", "西式", "下饭"],
        "healthStars": 4, "dietFriendly": True, "dietNote": "牛肉低脂，煎制比炸健康，适合增肌",
        "nutrition": {"calories": 300, "salt": 2.5, "protein": "高蛋白"},
    },
    {
        "id": "b008", "name": "牛肉炒面", "category": "牛肉类",
        "description": "面条筋道，牛肉香嫩，一盘管饱",
        "emoji": "🥩🍜", "prepTime": 10, "cookTime": 10,
        "ingredients": [
            {"name": "牛肉", "amount": 200, "unit": "g"},
            {"name": "面条", "amount": 200, "unit": "g"},
            {"name": "青椒", "amount": 100, "unit": "g"},
            {"name": "洋葱", "amount": 200, "unit": "g"},
        ],
        "seasonings": [
            {"name": "生抽", "amount": 15, "unit": "ml"},
            {"name": "老抽", "amount": 10, "unit": "ml"},
            {"name": "料酒", "amount": 10, "unit": "ml"},
            {"name": "蚝油", "amount": 10, "unit": "ml"},
            {"name": "食用油", "amount": 25, "unit": "ml"},
        ],
        "steps": [
            "牛肉逆纹切丝，加料酒、生抽、淀粉腌制",
            "面条煮至八分熟捞出过凉水沥干",
            "热锅多油，下牛肉丝滑炒至变色盛出",
            "锅中加油，炒香洋葱丝和青椒丝",
            "下面条大火翻炒，加生抽、老抽、蚝油",
            "倒回牛肉丝翻匀即可",
        ],
        "tags": ["主食", "下饭", "快手菜", "一人食"],
        "healthStars": 3, "dietFriendly": False, "dietNote": "炒面碳水较高，牛肉补充蛋白，运动后可吃",
        "nutrition": {"calories": 480, "salt": 3.0, "protein": "高蛋白"},
    },

    # ============================
    # 鱼虾类（约 8 道）
    # ============================
    {
        "id": "f001", "name": "清蒸鱼", "category": "鱼虾类",
        "description": "原汁原味，鱼肉鲜嫩，最简单的美味",
        "emoji": "🐟♨️", "prepTime": 10, "cookTime": 12,
        "ingredients": [
            {"name": "鱼", "amount": 500, "unit": "g"},
            {"name": "葱", "amount": 30, "unit": "g"},
            {"name": "生姜", "amount": 20, "unit": "g"},
        ],
        "seasonings": [
            {"name": "生抽", "amount": 20, "unit": "ml"},
            {"name": "料酒", "amount": 15, "unit": "ml"},
            {"name": "食用油", "amount": 20, "unit": "ml"},
            {"name": "盐", "amount": 3, "unit": "g"},
        ],
        "steps": [
            "鱼处理干净，两面各划三刀",
            "鱼身内外抹盐和料酒，腌制10分钟",
            "盘底铺姜片和葱段，鱼放上面",
            "鱼身上放姜丝",
            "水开后上锅大火蒸8-10分钟（看鱼的大小）",
            "倒掉盘中蒸出来的腥水",
            "鱼身上铺葱丝，淋上蒸鱼豉油或生抽",
            "另起锅烧热油，浇在葱丝上激出香味",
        ],
        "tags": ["经典", "健康", "清淡", "快手菜"],
        "healthStars": 5, "dietFriendly": True, "dietNote": "蒸制低脂高蛋白，非常适合减肥和增肌人群",
        "nutrition": {"calories": 200, "salt": 2.2, "protein": "高蛋白"},
    },
    {
        "id": "f002", "name": "红烧鱼", "category": "鱼虾类",
        "description": "色泽红亮，鱼肉入味，经典家常做法",
        "emoji": "🐟🍖", "prepTime": 10, "cookTime": 20,
        "ingredients": [
            {"name": "鱼", "amount": 500, "unit": "g"},
            {"name": "生姜", "amount": 15, "unit": "g"},
            {"name": "葱", "amount": 20, "unit": "g"},
            {"name": "大蒜", "amount": 10, "unit": "g"},
        ],
        "seasonings": [
            {"name": "生抽", "amount": 20, "unit": "ml"},
            {"name": "老抽", "amount": 10, "unit": "ml"},
            {"name": "料酒", "amount": 15, "unit": "ml"},
            {"name": "白糖", "amount": 10, "unit": "g"},
            {"name": "豆瓣酱", "amount": 15, "unit": "g"},
            {"name": "淀粉", "amount": 5, "unit": "g"},
            {"name": "食用油", "amount": 30, "unit": "ml"},
        ],
        "steps": [
            "鱼处理干净，两面各划三刀，抹料酒盐腌制",
            "用厨房纸吸干鱼身水分（防溅油）",
            "热锅热油，下鱼中火煎至两面金黄",
            "加姜片蒜瓣葱段爆香",
            "加料酒、生抽、老抽、白糖、豆瓣酱",
            "加热水至鱼身一半，中火煮10分钟",
            "中间把汤汁不停浇在鱼身上",
            "大火收汁，勾薄芡，汤汁浓稠出锅",
        ],
        "tags": ["经典", "下饭", "家常"],
        "healthStars": 4, "dietFriendly": True, "dietNote": "鱼肉高蛋白低脂，红烧稍增热量但依然健康",
        "nutrition": {"calories": 300, "salt": 3.0, "protein": "高蛋白"},
    },
    {
        "id": "f003", "name": "糖醋鱼", "category": "鱼虾类",
        "description": "酸甜可口，外酥里嫩，宴客大菜",
        "emoji": "🐟🍬", "prepTime": 15, "cookTime": 15,
        "ingredients": [
            {"name": "鱼", "amount": 500, "unit": "g"},
            {"name": "生姜", "amount": 10, "unit": "g"},
            {"name": "葱", "amount": 10, "unit": "g"},
        ],
        "seasonings": [
            {"name": "淀粉", "amount": 100, "unit": "g"},
            {"name": "白糖", "amount": 40, "unit": "g"},
            {"name": "醋", "amount": 40, "unit": "ml"},
            {"name": "番茄酱", "amount": 30, "unit": "g"},
            {"name": "生抽", "amount": 10, "unit": "ml"},
            {"name": "料酒", "amount": 15, "unit": "ml"},
            {"name": "食用油", "amount": 300, "unit": "ml"},
        ],
        "steps": [
            "鱼处理干净，切牡丹花刀，加料酒盐腌制",
            "鱼身拍上干淀粉",
            "油温七成热，下鱼炸至金黄定型捞出",
            "油温升高复炸至酥脆",
            "另起锅：番茄酱+糖+醋+生抽+水煮开",
            "勾芡使糖醋汁浓稠",
            "将糖醋汁均匀浇在鱼身上",
            "撒葱丝和姜丝装饰",
        ],
        "tags": ["经典", "宴客", "酸甜"],
        "healthStars": 3, "dietFriendly": False, "dietNote": "油炸高油高糖，减肥期间不建议食用",
        "nutrition": {"calories": 480, "salt": 2.5, "protein": "高蛋白"},
    },
    {
        "id": "f004", "name": "蒜蓉虾", "category": "鱼虾类",
        "description": "蒜香扑鼻，虾肉Q弹，简单又高级",
        "emoji": "🦐🧄", "prepTime": 15, "cookTime": 8,
        "ingredients": [
            {"name": "虾", "amount": 300, "unit": "g"},
            {"name": "大蒜", "amount": 30, "unit": "g"},
            {"name": "葱", "amount": 10, "unit": "g"},
        ],
        "seasonings": [
            {"name": "生抽", "amount": 10, "unit": "ml"},
            {"name": "料酒", "amount": 10, "unit": "ml"},
            {"name": "食用油", "amount": 20, "unit": "ml"},
            {"name": "盐", "amount": 2, "unit": "g"},
        ],
        "steps": [
            "虾剪去须脚，开背去虾线",
            "大蒜剁成蒜蓉（越细越好）",
            "虾加料酒、少许盐腌制5分钟",
            "热锅加油，小火炒香一半蒜蓉至金黄",
            "下虾翻炒至变红",
            "加剩余的生蒜蓉、生抽翻炒",
            "撒葱花出锅",
        ],
        "tags": ["快手菜", "下饭", "宴客", "海鲜"],
        "healthStars": 4, "dietFriendly": True, "dietNote": "虾低脂高蛋白，蒜蓉做法少油，很健康",
        "nutrition": {"calories": 180, "salt": 2.0, "protein": "高蛋白"},
    },
    {
        "id": "f005", "name": "白灼虾", "category": "鱼虾类",
        "description": "最简单的做法，最鲜甜的味道，蘸料是灵魂",
        "emoji": "🦐💧", "prepTime": 5, "cookTime": 5,
        "ingredients": [
            {"name": "虾", "amount": 300, "unit": "g"},
            {"name": "生姜", "amount": 15, "unit": "g"},
            {"name": "葱", "amount": 10, "unit": "g"},
        ],
        "seasonings": [
            {"name": "生抽", "amount": 20, "unit": "ml"},
            {"name": "料酒", "amount": 15, "unit": "ml"},
            {"name": "食用油", "amount": 10, "unit": "ml"},
        ],
        "steps": [
            "虾剪去须脚，挑去虾线",
            "锅中烧水，加姜片葱段料酒",
            "水开后下虾，煮至变红弯曲（约2-3分钟）",
            "捞出浸冰水（肉更Q弹）",
            "蘸料：姜末+生抽+少许热油",
            "虾摆盘，蘸料放中间",
        ],
        "tags": ["快手菜", "健康", "海鲜", "清淡"],
        "healthStars": 5, "dietFriendly": True, "dietNote": "白灼零油，虾低脂高蛋白，最健康的吃法",
        "nutrition": {"calories": 130, "salt": 1.5, "protein": "高蛋白"},
    },
    {
        "id": "f006", "name": "炒蛤蜊", "category": "鱼虾类",
        "description": "鲜味十足，简单快炒，配啤酒一绝",
        "emoji": "🐚🌶️", "prepTime": 20, "cookTime": 5,
        "ingredients": [
            {"name": "蛤蜊", "amount": 500, "unit": "g"},
            {"name": "大蒜", "amount": 15, "unit": "g"},
            {"name": "干辣椒", "amount": 5, "unit": "g"},
            {"name": "生姜", "amount": 10, "unit": "g"},
            {"name": "葱", "amount": 15, "unit": "g"},
        ],
        "seasonings": [
            {"name": "生抽", "amount": 10, "unit": "ml"},
            {"name": "料酒", "amount": 15, "unit": "ml"},
            {"name": "食用油", "amount": 20, "unit": "ml"},
        ],
        "steps": [
            "蛤蜊用淡盐水浸泡2小时吐沙（或直接买吐好沙的）",
            "蒜切末，姜切丝，干辣椒剪段",
            "热锅加油，爆香蒜末、姜丝、干辣椒",
            "蛤蜊沥干水下锅，大火快速翻炒",
            "加料酒去腥，加盖焖1分钟",
            "蛤蜊开口后加生抽翻匀",
            "撒葱段出锅（不开口的死蛤蜊挑掉不吃）",
        ],
        "tags": ["快手菜", "海鲜", "下饭", "夜市"],
        "healthStars": 4, "dietFriendly": True, "dietNote": "蛤蜊低脂高蛋白，做法清淡，适合减肥",
        "nutrition": {"calories": 160, "salt": 2.5, "protein": "高蛋白"},
    },
    {
        "id": "f007", "name": "水煮鱼片", "category": "鱼虾类",
        "description": "麻辣鲜香，鱼片嫩滑，川菜经典",
        "emoji": "🐟🌶️", "prepTime": 15, "cookTime": 15,
        "ingredients": [
            {"name": "鱼", "amount": 500, "unit": "g"},
            {"name": "豆芽", "amount": 300, "unit": "g"},
            {"name": "干辣椒", "amount": 20, "unit": "g"},
            {"name": "花椒", "amount": 10, "unit": "g"},
            {"name": "大蒜", "amount": 15, "unit": "g"},
            {"name": "生姜", "amount": 15, "unit": "g"},
        ],
        "seasonings": [
            {"name": "豆瓣酱", "amount": 30, "unit": "g"},
            {"name": "生抽", "amount": 15, "unit": "ml"},
            {"name": "料酒", "amount": 20, "unit": "ml"},
            {"name": "淀粉", "amount": 20, "unit": "g"},
            {"name": "食用油", "amount": 50, "unit": "ml"},
        ],
        "steps": [
            "鱼去骨取肉，斜刀片薄片",
            "鱼片加料酒、盐、淀粉、蛋清抓匀腌15分钟",
            "豆芽焯水铺大碗底",
            "热锅加油，下豆瓣酱炒出红油",
            "加姜蒜末爆香，加水烧开",
            "转小火，一片片下鱼片煮至变白（约1分钟）",
            "连汤倒在豆芽上",
            "撒干辣椒段花椒和蒜末",
            "另起锅烧热油，泼在辣椒上",
        ],
        "tags": ["辣", "经典", "川菜", "硬菜"],
        "healthStars": 3, "dietFriendly": False, "dietNote": "油多辣重，但鱼肉本身健康，可少油改良",
        "nutrition": {"calories": 350, "salt": 3.5, "protein": "高蛋白"},
    },
    {
        "id": "f008", "name": "番茄虾仁", "category": "鱼虾类",
        "description": "酸甜开胃，虾仁Q弹，红白相间颜值高",
        "emoji": "🍅🦐", "prepTime": 10, "cookTime": 10,
        "ingredients": [
            {"name": "虾仁", "amount": 200, "unit": "g"},
            {"name": "番茄", "amount": 300, "unit": "g"},
            {"name": "葱", "amount": 10, "unit": "g"},
        ],
        "seasonings": [
            {"name": "料酒", "amount": 10, "unit": "ml"},
            {"name": "白糖", "amount": 5, "unit": "g"},
            {"name": "食用油", "amount": 15, "unit": "ml"},
            {"name": "盐", "amount": 2, "unit": "g"},
        ],
        "steps": [
            "虾仁加料酒、少许盐腌制10分钟",
            "番茄切块，葱切花",
            "热锅加油，下虾仁滑炒至变红盛出",
            "锅中下番茄块，中火炒至出汁",
            "加白糖和少许水煮至番茄软烂",
            "倒回虾仁翻炒均匀",
            "撒葱花出锅",
        ],
        "tags": ["快手菜", "下饭", "健康", "家常"],
        "healthStars": 5, "dietFriendly": True, "dietNote": "低脂低热量，番茄和虾仁都是减脂好食材",
        "nutrition": {"calories": 160, "salt": 1.2, "protein": "高蛋白"},
    },

    # ============================
    # 豆腐类（约 10 道）
    # ============================
    {
        "id": "t001", "name": "麻婆豆腐", "category": "豆腐类",
        "description": "麻辣鲜香烫，豆腐嫩滑，米饭一碗不够",
        "emoji": "🧈🌶️", "prepTime": 5, "cookTime": 10,
        "ingredients": [
            {"name": "豆腐", "amount": 300, "unit": "g"},
            {"name": "猪肉", "amount": 100, "unit": "g"},
            {"name": "葱", "amount": 10, "unit": "g"},
            {"name": "大蒜", "amount": 10, "unit": "g"},
        ],
        "seasonings": [
            {"name": "豆瓣酱", "amount": 20, "unit": "g"},
            {"name": "生抽", "amount": 10, "unit": "ml"},
            {"name": "淀粉", "amount": 10, "unit": "g"},
            {"name": "花椒", "amount": 3, "unit": "g"},
            {"name": "食用油", "amount": 20, "unit": "ml"},
        ],
        "steps": [
            "豆腐切2cm方块，开水加盐焯烫2分钟捞出",
            "猪肉剁成肉末，蒜切末",
            "热锅加油，下肉末炒散至出油",
            "加豆瓣酱炒出红油，加蒜末炒香",
            "加水和生抽烧开，轻轻放入豆腐",
            "中小火煮5分钟让豆腐入味",
            "用水淀粉勾芡，分两次加（更挂味）",
            "出锅撒花椒粉和葱花",
        ],
        "tags": ["经典", "下饭", "川菜", "快手菜"],
        "healthStars": 3, "dietFriendly": True, "dietNote": "豆腐低脂高蛋白，少油少肉可做减脂改良版",
        "nutrition": {"calories": 280, "salt": 3.0, "protein": "高蛋白"},
    },
    {
        "id": "t002", "name": "家常豆腐", "category": "豆腐类",
        "description": "外焦里嫩，家常口味，简单好吃",
        "emoji": "🧈🥬", "prepTime": 5, "cookTime": 10,
        "ingredients": [
            {"name": "老豆腐", "amount": 300, "unit": "g"},
            {"name": "青椒", "amount": 100, "unit": "g"},
            {"name": "胡萝卜", "amount": 50, "unit": "g"},
            {"name": "大蒜", "amount": 10, "unit": "g"},
        ],
        "seasonings": [
            {"name": "生抽", "amount": 15, "unit": "ml"},
            {"name": "老抽", "amount": 5, "unit": "ml"},
            {"name": "蚝油", "amount": 10, "unit": "ml"},
            {"name": "淀粉", "amount": 5, "unit": "g"},
            {"name": "食用油", "amount": 25, "unit": "ml"},
        ],
        "steps": [
            "老豆腐切三角片（约0.5cm厚）",
            "青椒胡萝卜切片，蒜切片",
            "热锅多油，下豆腐片煎至两面金黄盛出",
            "锅中留油，爆香蒜片，下胡萝卜青椒翻炒",
            "加生抽、老抽、蚝油和少量水烧开",
            "放入煎好的豆腐，翻匀煮1分钟入味",
            "用水淀粉勾芡出锅",
        ],
        "tags": ["家常", "下饭", "快手菜", "素菜"],
        "healthStars": 4, "dietFriendly": True, "dietNote": "豆腐低脂高蛋白，煎制比炸健康",
        "nutrition": {"calories": 250, "salt": 2.3, "protein": "中蛋白"},
    },
    {
        "id": "t003", "name": "凉拌豆腐", "category": "豆腐类",
        "description": "清爽开胃，无需开火，夏天最爱",
        "emoji": "🧈❄️", "prepTime": 5, "cookTime": 0,
        "ingredients": [
            {"name": "嫩豆腐", "amount": 300, "unit": "g"},
            {"name": "葱", "amount": 10, "unit": "g"},
            {"name": "大蒜", "amount": 5, "unit": "g"},
            {"name": "皮蛋", "amount": 60, "unit": "g"},
        ],
        "seasonings": [
            {"name": "生抽", "amount": 15, "unit": "ml"},
            {"name": "醋", "amount": 10, "unit": "ml"},
            {"name": "白糖", "amount": 3, "unit": "g"},
            {"name": "食用油", "amount": 10, "unit": "ml"},
        ],
        "steps": [
            "嫩豆腐从盒中取出，完整扣在盘中",
            "皮蛋切小丁，蒜切末，葱切花",
            "豆腐上铺上皮蛋丁",
            "调汁：生抽+醋+白糖+蒜末混合",
            "将汁浇在豆腐上",
            "热油浇在葱花上激香即可",
        ],
        "tags": ["快手菜", "凉菜", "清爽", "夏季", "无需开火"],
        "healthStars": 5, "dietFriendly": True, "dietNote": "零油烟，低热量高蛋白，减肥最佳选择",
        "nutrition": {"calories": 150, "salt": 2.0, "protein": "高蛋白"},
    },
    {
        "id": "t004", "name": "皮蛋豆腐", "category": "豆腐类",
        "description": "经典凉菜，无需开火，三分钟搞定",
        "emoji": "🥚🧈", "prepTime": 3, "cookTime": 0,
        "ingredients": [
            {"name": "嫩豆腐", "amount": 300, "unit": "g"},
            {"name": "皮蛋", "amount": 120, "unit": "g"},
            {"name": "葱", "amount": 10, "unit": "g"},
        ],
        "seasonings": [
            {"name": "生抽", "amount": 15, "unit": "ml"},
            {"name": "醋", "amount": 10, "unit": "ml"},
            {"name": "白糖", "amount": 3, "unit": "g"},
            {"name": "食用油", "amount": 10, "unit": "ml"},
        ],
        "steps": [
            "嫩豆腐完整扣入盘中",
            "皮蛋剥壳切小块，铺在豆腐上和周围",
            "生抽+醋+白糖调成汁",
            "浇汁，撒葱花和蒜末",
            "烧热油浇在葱花上激香",
        ],
        "tags": ["凉菜", "快手菜", "夏季", "无需开火"],
        "healthStars": 4, "dietFriendly": True, "dietNote": "零油烟凉菜，豆腐低脂，夏天吃清爽",
        "nutrition": {"calories": 160, "salt": 2.5, "protein": "高蛋白"},
    },
    {
        "id": "t005", "name": "豆腐汤", "category": "豆腐类",
        "description": "清淡鲜美，暖心暖胃，配什么菜都行",
        "emoji": "🧈🍲", "prepTime": 5, "cookTime": 10,
        "ingredients": [
            {"name": "豆腐", "amount": 200, "unit": "g"},
            {"name": "鸡蛋", "amount": 55, "unit": "g"},
            {"name": "葱", "amount": 10, "unit": "g"},
            {"name": "蘑菇", "amount": 50, "unit": "g"},
        ],
        "seasonings": [
            {"name": "生抽", "amount": 5, "unit": "ml"},
            {"name": "食用油", "amount": 5, "unit": "ml"},
            {"name": "盐", "amount": 2, "unit": "g"},
        ],
        "steps": [
            "豆腐切小块，蘑菇切片，鸡蛋打散",
            "锅中少油炒蘑菇片至出香",
            "加水烧开，下豆腐块煮3分钟",
            "淋入蛋液形成蛋花",
            "加生抽和盐调味，撒葱花出锅",
        ],
        "tags": ["汤", "快手菜", "清淡", "一人食"],
        "healthStars": 5, "dietFriendly": True, "dietNote": "低脂低热量，一碗汤暖胃不增重",
        "nutrition": {"calories": 100, "salt": 1.2, "protein": "中蛋白"},
    },
    {
        "id": "t006", "name": "红烧豆腐", "category": "豆腐类",
        "description": "酱香浓郁，豆腐入味，简单下饭",
        "emoji": "🧈🍖", "prepTime": 5, "cookTime": 10,
        "ingredients": [
            {"name": "老豆腐", "amount": 300, "unit": "g"},
            {"name": "猪肉", "amount": 100, "unit": "g"},
            {"name": "葱", "amount": 10, "unit": "g"},
            {"name": "大蒜", "amount": 10, "unit": "g"},
        ],
        "seasonings": [
            {"name": "生抽", "amount": 15, "unit": "ml"},
            {"name": "老抽", "amount": 10, "unit": "ml"},
            {"name": "豆瓣酱", "amount": 15, "unit": "g"},
            {"name": "白糖", "amount": 5, "unit": "g"},
            {"name": "淀粉", "amount": 5, "unit": "g"},
            {"name": "食用油", "amount": 25, "unit": "ml"},
        ],
        "steps": [
            "老豆腐切厚片，开水烫一下去豆腥味",
            "猪肉剁末，蒜切片",
            "热锅加油，下豆腐片中火煎至两面金黄",
            "盛出豆腐，留油下肉末炒散",
            "加豆瓣酱和蒜片炒香",
            "加生抽、老抽、白糖和少量水",
            "放回豆腐，翻匀煮2分钟入味",
            "水淀粉勾芡，撒葱花出锅",
        ],
        "tags": ["家常", "下饭", "快手菜"],
        "healthStars": 4, "dietFriendly": True, "dietNote": "少肉多豆腐的健康搭配，适量食用适合减肥",
        "nutrition": {"calories": 300, "salt": 2.8, "protein": "高蛋白"},
    },
    {
        "id": "t007", "name": "锅塌豆腐", "category": "豆腐类",
        "description": "蛋香浓郁，豆腐软嫩，老北京经典",
        "emoji": "🧈🥚", "prepTime": 5, "cookTime": 10,
        "ingredients": [
            {"name": "老豆腐", "amount": 300, "unit": "g"},
            {"name": "鸡蛋", "amount": 110, "unit": "g"},
            {"name": "葱", "amount": 10, "unit": "g"},
        ],
        "seasonings": [
            {"name": "生抽", "amount": 10, "unit": "ml"},
            {"name": "蚝油", "amount": 10, "unit": "ml"},
            {"name": "食用油", "amount": 20, "unit": "ml"},
            {"name": "盐", "amount": 2, "unit": "g"},
        ],
        "steps": [
            "老豆腐切1cm厚片，鸡蛋打散",
            "豆腐片裹上蛋液",
            "热锅加油，下豆腐片煎至两面金黄",
            "淋入剩余蛋液，晃动锅让蛋液均匀",
            "加生抽、蚝油和少量水",
            "小火焖2分钟让豆腐吸收汤汁",
            "出锅前撒葱花",
        ],
        "tags": ["家常", "快手菜", "经典", "北京菜"],
        "healthStars": 4, "dietFriendly": True, "dietNote": "蛋和豆腐都是优质蛋白，做法简单健康",
        "nutrition": {"calories": 240, "salt": 2.0, "protein": "高蛋白"},
    },
    {
        "id": "t008", "name": "鱼香豆腐", "category": "豆腐类",
        "description": "鱼香味型配豆腐，酸甜微辣，素菜也能很下饭",
        "emoji": "🧈🥕", "prepTime": 5, "cookTime": 10,
        "ingredients": [
            {"name": "老豆腐", "amount": 300, "unit": "g"},
            {"name": "胡萝卜", "amount": 50, "unit": "g"},
            {"name": "木耳", "amount": 30, "unit": "g"},
            {"name": "葱", "amount": 10, "unit": "g"},
            {"name": "大蒜", "amount": 10, "unit": "g"},
        ],
        "seasonings": [
            {"name": "生抽", "amount": 15, "unit": "ml"},
            {"name": "醋", "amount": 15, "unit": "ml"},
            {"name": "白糖", "amount": 10, "unit": "g"},
            {"name": "豆瓣酱", "amount": 10, "unit": "g"},
            {"name": "淀粉", "amount": 10, "unit": "g"},
            {"name": "食用油", "amount": 20, "unit": "ml"},
        ],
        "steps": [
            "豆腐切块焯水，胡萝卜切丝，木耳泡发切丝",
            "调鱼香汁：生抽+醋+糖+淀粉+水",
            "热锅加油，下豆瓣酱炒出红油",
            "下蒜末、胡萝卜丝、木耳丝翻炒",
            "加豆腐块轻轻翻炒",
            "淋入鱼香汁，大火收汁",
            "撒葱花出锅",
        ],
        "tags": ["下饭", "素菜", "经典"],
        "healthStars": 4, "dietFriendly": True, "dietNote": "素食版鱼香，豆腐低脂，少油更健康",
        "nutrition": {"calories": 230, "salt": 2.5, "protein": "中蛋白"},
    },
    {
        "id": "t009", "name": "白菜豆腐", "category": "豆腐类",
        "description": "清清爽爽，白绿相间，最朴素的家常美味",
        "emoji": "🥬🧈", "prepTime": 5, "cookTime": 10,
        "ingredients": [
            {"name": "豆腐", "amount": 200, "unit": "g"},
            {"name": "白菜", "amount": 300, "unit": "g"},
            {"name": "葱", "amount": 5, "unit": "g"},
        ],
        "seasonings": [
            {"name": "生抽", "amount": 10, "unit": "ml"},
            {"name": "食用油", "amount": 15, "unit": "ml"},
            {"name": "盐", "amount": 2, "unit": "g"},
        ],
        "steps": [
            "豆腐切块，白菜切段",
            "热锅加油，下白菜翻炒至变软",
            "加豆腐块轻轻翻匀",
            "加生抽和少量水",
            "加盖焖3分钟至白菜出水",
            "盐调味出锅",
        ],
        "tags": ["家常", "清淡", "快手菜", "素"],
        "healthStars": 5, "dietFriendly": True, "dietNote": "低脂低热量，豆腐和白菜都是健康食材",
        "nutrition": {"calories": 120, "salt": 1.2, "protein": "中蛋白"},
    },
    {
        "id": "t010", "name": "葱烧豆腐", "category": "豆腐类",
        "description": "葱香浓郁，豆腐入味，极其下饭",
        "emoji": "🧈🧅", "prepTime": 5, "cookTime": 10,
        "ingredients": [
            {"name": "老豆腐", "amount": 300, "unit": "g"},
            {"name": "葱", "amount": 50, "unit": "g"},
        ],
        "seasonings": [
            {"name": "生抽", "amount": 15, "unit": "ml"},
            {"name": "老抽", "amount": 5, "unit": "ml"},
            {"name": "蚝油", "amount": 10, "unit": "ml"},
            {"name": "白糖", "amount": 3, "unit": "g"},
            {"name": "食用油", "amount": 20, "unit": "ml"},
        ],
        "steps": [
            "老豆腐切厚片，大葱切段",
            "热锅加油，下豆腐片煎至两面金黄",
            "下葱段煎出香味",
            "加生抽、老抽、蚝油、白糖和少量水",
            "翻匀煮2分钟入味",
            "汤汁收浓即可出锅",
        ],
        "tags": ["快手菜", "下饭", "家常", "素菜"],
        "healthStars": 4, "dietFriendly": True, "dietNote": "豆腐低脂，葱增香不增热量，健康简单",
        "nutrition": {"calories": 200, "salt": 2.2, "protein": "中蛋白"},
    },

    # ============================
    # 蔬菜类（约 12 道）
    # ============================
    {
        "id": "g001", "name": "蒜蓉西兰花", "category": "蔬菜类",
        "description": "翠绿爽口，蒜香清新，最健康的蔬菜做法",
        "emoji": "🥦🧄", "prepTime": 5, "cookTime": 5,
        "ingredients": [
            {"name": "西兰花", "amount": 300, "unit": "g"},
            {"name": "大蒜", "amount": 15, "unit": "g"},
        ],
        "seasonings": [
            {"name": "生抽", "amount": 10, "unit": "ml"},
            {"name": "蚝油", "amount": 10, "unit": "ml"},
            {"name": "食用油", "amount": 15, "unit": "ml"},
            {"name": "盐", "amount": 2, "unit": "g"},
        ],
        "steps": [
            "西兰花掰小朵，淡盐水浸泡10分钟",
            "开水加少许盐和油，焯西兰花2分钟捞出",
            "蒜切末",
            "热锅少油，小火炒香蒜末",
            "下西兰花翻炒",
            "加蚝油、盐翻匀即可",
        ],
        "tags": ["快手菜", "健康", "素菜", "清淡"],
        "healthStars": 5, "dietFriendly": True, "dietNote": "零油腻感，西兰花营养密集，减肥必备",
        "nutrition": {"calories": 80, "salt": 1.0, "protein": "低蛋白"},
    },
    {
        "id": "g002", "name": "干煸四季豆", "category": "蔬菜类",
        "description": "干香入味，外皮微焦，下饭素菜第一名",
        "emoji": "🫘🧄", "prepTime": 5, "cookTime": 12,
        "ingredients": [
            {"name": "四季豆", "amount": 300, "unit": "g"},
            {"name": "大蒜", "amount": 10, "unit": "g"},
            {"name": "干辣椒", "amount": 5, "unit": "g"},
            {"name": "猪肉", "amount": 50, "unit": "g"},
        ],
        "seasonings": [
            {"name": "生抽", "amount": 15, "unit": "ml"},
            {"name": "老抽", "amount": 5, "unit": "ml"},
            {"name": "食用油", "amount": 25, "unit": "ml"},
            {"name": "盐", "amount": 2, "unit": "g"},
        ],
        "steps": [
            "四季豆去两头和筋，掰成段，洗净沥干",
            "猪肉切末，蒜切片，干辣椒剪段",
            "热锅多油，下四季豆中小火煸炒（关键步骤）",
            "持续煸炒至表皮起皱变焦黄（约8分钟）",
            "煸好的豆子推到一边，下肉末炒散",
            "加蒜片干辣椒炒香",
            "加生抽、老抽、盐翻匀出锅",
        ],
        "tags": ["下饭", "经典", "素菜"],
        "healthStars": 3, "dietFriendly": True, "dietNote": "油偏多但四季豆本身健康，少油改良更佳",
        "nutrition": {"calories": 180, "salt": 1.8, "protein": "中蛋白"},
    },
    {
        "id": "g003", "name": "醋溜白菜", "category": "蔬菜类",
        "description": "酸脆爽口，开胃下饭，三分钟快手菜",
        "emoji": "🥬🍶", "prepTime": 5, "cookTime": 5,
        "ingredients": [
            {"name": "白菜", "amount": 400, "unit": "g"},
            {"name": "大蒜", "amount": 10, "unit": "g"},
            {"name": "干辣椒", "amount": 5, "unit": "g"},
        ],
        "seasonings": [
            {"name": "醋", "amount": 20, "unit": "ml"},
            {"name": "生抽", "amount": 10, "unit": "ml"},
            {"name": "白糖", "amount": 3, "unit": "g"},
            {"name": "淀粉", "amount": 5, "unit": "g"},
            {"name": "食用油", "amount": 20, "unit": "ml"},
        ],
        "steps": [
            "白菜帮和叶分开，帮斜切薄片，叶撕块",
            "蒜切片，干辣椒剪段",
            "热锅加油，爆香蒜片和干辣椒",
            "先下白菜帮大火翻炒1分钟",
            "再下白菜叶翻炒至变软",
            "加醋、生抽、白糖，翻匀",
            "水淀粉勾芡后立刻出锅（保持脆感）",
        ],
        "tags": ["快手菜", "下饭", "素菜", "酸"],
        "healthStars": 5, "dietFriendly": True, "dietNote": "低热量低脂，醋有助消化，减肥友好",
        "nutrition": {"calories": 80, "salt": 0.8, "protein": "低蛋白"},
    },
    {
        "id": "g004", "name": "地三鲜", "category": "蔬菜类",
        "description": "东北招牌素菜，茄子土豆青椒三兄弟",
        "emoji": "🍆🥔🫑", "prepTime": 10, "cookTime": 15,
        "ingredients": [
            {"name": "茄子", "amount": 250, "unit": "g"},
            {"name": "土豆", "amount": 200, "unit": "g"},
            {"name": "青椒", "amount": 100, "unit": "g"},
            {"name": "大蒜", "amount": 10, "unit": "g"},
            {"name": "葱", "amount": 10, "unit": "g"},
        ],
        "seasonings": [
            {"name": "生抽", "amount": 15, "unit": "ml"},
            {"name": "老抽", "amount": 5, "unit": "ml"},
            {"name": "蚝油", "amount": 10, "unit": "ml"},
            {"name": "白糖", "amount": 5, "unit": "g"},
            {"name": "淀粉", "amount": 10, "unit": "g"},
            {"name": "食用油", "amount": 30, "unit": "ml"},
        ],
        "steps": [
            "土豆去皮切滚刀块，茄子切滚刀块，青椒切块",
            "茄子撒盐腌制10分钟挤去水分（减少吸油）",
            "热锅多油，下土豆块煎至金黄盛出",
            "同锅下茄子块煎软盛出",
            "留底油爆香蒜末葱花",
            "下青椒翻炒",
            "倒回土豆茄子，加生抽、老抽、蚝油、白糖",
            "翻炒均匀，水淀粉勾芡出锅",
        ],
        "tags": ["经典", "下饭", "素菜", "东北菜"],
        "healthStars": 3, "dietFriendly": False, "dietNote": "传统做法需过油，热量较高，少油煎制可改良",
        "nutrition": {"calories": 280, "salt": 2.2, "protein": "低蛋白"},
    },
    {
        "id": "g005", "name": "酸辣土豆丝", "category": "蔬菜类",
        "description": "国民小炒，酸辣开胃，脆爽可口",
        "emoji": "🥔🌶️", "prepTime": 10, "cookTime": 5,
        "ingredients": [
            {"name": "土豆", "amount": 400, "unit": "g"},
            {"name": "青椒", "amount": 50, "unit": "g"},
            {"name": "干辣椒", "amount": 5, "unit": "g"},
            {"name": "大蒜", "amount": 10, "unit": "g"},
        ],
        "seasonings": [
            {"name": "醋", "amount": 20, "unit": "ml"},
            {"name": "生抽", "amount": 10, "unit": "ml"},
            {"name": "食用油", "amount": 20, "unit": "ml"},
            {"name": "盐", "amount": 3, "unit": "g"},
        ],
        "steps": [
            "土豆去皮切细丝（约火柴棍粗细）",
            "土豆丝泡清水洗去淀粉，换两次水",
            "沥干水分（炒出来才脆）",
            "青椒切丝，蒜切片，干辣椒剪段",
            "热锅热油，爆香蒜片和干辣椒",
            "下土豆丝大火快炒1分钟",
            "淋入醋（先放醋才脆），加生抽和盐",
            "下青椒丝，大火翻炒30秒出锅",
        ],
        "tags": ["快手菜", "经典", "下饭", "素菜"],
        "healthStars": 4, "dietFriendly": True, "dietNote": "土豆碳水适中，少油炒制很健康",
        "nutrition": {"calories": 160, "salt": 1.5, "protein": "低蛋白"},
    },
    {
        "id": "g006", "name": "凉拌黄瓜", "category": "蔬菜类",
        "description": "拍一拍就搞定，夏日必备开胃凉菜",
        "emoji": "🥒🧄", "prepTime": 5, "cookTime": 0,
        "ingredients": [
            {"name": "黄瓜", "amount": 400, "unit": "g"},
            {"name": "大蒜", "amount": 15, "unit": "g"},
        ],
        "seasonings": [
            {"name": "生抽", "amount": 15, "unit": "ml"},
            {"name": "醋", "amount": 15, "unit": "ml"},
            {"name": "白糖", "amount": 3, "unit": "g"},
            {"name": "食用油", "amount": 10, "unit": "ml"},
        ],
        "steps": [
            "黄瓜洗净，用刀背拍裂（别拍太碎）",
            "切成小段放入碗中",
            "蒜剁成蒜末",
            "碗中加蒜末、生抽、醋、白糖",
            "烧热油浇在蒜末上激香",
            "拌匀腌制5分钟即可食用",
        ],
        "tags": ["凉菜", "快手菜", "清爽", "夏季", "无需开火"],
        "healthStars": 5, "dietFriendly": True, "dietNote": "最低热量，最适合减肥期间吃的菜之一",
        "nutrition": {"calories": 60, "salt": 1.0, "protein": "低蛋白"},
    },
    {
        "id": "g007", "name": "蒜蓉菠菜", "category": "蔬菜类",
        "description": "简单快手，蒜香配菠菜，营养又美味",
        "emoji": "🥬🧄", "prepTime": 5, "cookTime": 3,
        "ingredients": [
            {"name": "菠菜", "amount": 300, "unit": "g"},
            {"name": "大蒜", "amount": 15, "unit": "g"},
        ],
        "seasonings": [
            {"name": "生抽", "amount": 10, "unit": "ml"},
            {"name": "食用油", "amount": 15, "unit": "ml"},
            {"name": "盐", "amount": 2, "unit": "g"},
        ],
        "steps": [
            "菠菜去根洗净，开水加盐焯烫30秒捞出",
            "焯好的菠菜过凉水，挤干水分",
            "蒜切末",
            "热锅加油，小火炒香蒜末至微黄",
            "下菠菜快速翻炒",
            "加生抽和盐翻匀即可",
        ],
        "tags": ["快手菜", "健康", "素菜", "清淡"],
        "healthStars": 5, "dietFriendly": True, "dietNote": "极低热量，菠菜富含铁和维生素，减肥必备",
        "nutrition": {"calories": 70, "salt": 0.8, "protein": "低蛋白"},
    },
    {
        "id": "g008", "name": "炒豆芽", "category": "蔬菜类",
        "description": "清脆爽口，简单快手，两块钱搞定一道菜",
        "emoji": "🌱🧄", "prepTime": 5, "cookTime": 3,
        "ingredients": [
            {"name": "豆芽", "amount": 400, "unit": "g"},
            {"name": "葱", "amount": 10, "unit": "g"},
            {"name": "大蒜", "amount": 5, "unit": "g"},
        ],
        "seasonings": [
            {"name": "生抽", "amount": 10, "unit": "ml"},
            {"name": "醋", "amount": 5, "unit": "ml"},
            {"name": "食用油", "amount": 15, "unit": "ml"},
            {"name": "盐", "amount": 2, "unit": "g"},
        ],
        "steps": [
            "豆芽洗净沥干（一定要沥干水）",
            "葱切段，蒜切片",
            "热锅热油，爆香葱蒜",
            "下豆芽大火爆炒2分钟",
            "加生抽、醋、盐",
            "快速翻匀马上出锅（炒久了出水就不脆了）",
        ],
        "tags": ["快手菜", "素菜", "便宜", "一人食"],
        "healthStars": 5, "dietFriendly": True, "dietNote": "极低热量高纤维，减肥期间最推荐的蔬菜之一",
        "nutrition": {"calories": 60, "salt": 0.6, "protein": "低蛋白"},
    },
    {
        "id": "g009", "name": "清炒时蔬", "category": "蔬菜类",
        "description": "万能炒蔬菜模板，什么青菜都能这样做",
        "emoji": "🥬🧄", "prepTime": 5, "cookTime": 3,
        "ingredients": [
            {"name": "生菜", "amount": 300, "unit": "g"},
            {"name": "大蒜", "amount": 10, "unit": "g"},
        ],
        "seasonings": [
            {"name": "生抽", "amount": 10, "unit": "ml"},
            {"name": "食用油", "amount": 15, "unit": "ml"},
            {"name": "盐", "amount": 2, "unit": "g"},
        ],
        "steps": [
            "青菜洗净切段，蒜切末",
            "热锅热油，爆香蒜末",
            "下青菜大火快炒1-2分钟",
            "加生抽和盐调味",
            "青菜变软出水即可出锅",
        ],
        "tags": ["快手菜", "素菜", "清淡", "一人食", "通用"],
        "healthStars": 5, "dietFriendly": True, "dietNote": "任何蔬菜都适合这样炒，低脂低热量",
        "nutrition": {"calories": 60, "salt": 0.7, "protein": "低蛋白"},
    },
    {
        "id": "g010", "name": "番茄炒菜花", "category": "蔬菜类",
        "description": "酸甜清爽，菜花吸满番茄汁，好吃不胖",
        "emoji": "🍅🥦", "prepTime": 5, "cookTime": 10,
        "ingredients": [
            {"name": "西兰花", "amount": 200, "unit": "g"},
            {"name": "番茄", "amount": 300, "unit": "g"},
            {"name": "大蒜", "amount": 10, "unit": "g"},
        ],
        "seasonings": [
            {"name": "生抽", "amount": 10, "unit": "ml"},
            {"name": "白糖", "amount": 3, "unit": "g"},
            {"name": "食用油", "amount": 15, "unit": "ml"},
            {"name": "盐", "amount": 2, "unit": "g"},
        ],
        "steps": [
            "菜花掰小朵焯水1分钟，番茄切块",
            "热锅加油，爆香蒜末",
            "下番茄块中火炒至出汁",
            "加白糖辅助出汁",
            "下菜花翻炒均匀",
            "加生抽和盐，煮2分钟入味即可",
        ],
        "tags": ["家常", "素菜", "健康", "快手菜"],
        "healthStars": 5, "dietFriendly": True, "dietNote": "番茄维C丰富，低热量，非常适合减肥",
        "nutrition": {"calories": 90, "salt": 0.8, "protein": "低蛋白"},
    },
    {
        "id": "g011", "name": "香菇青菜", "category": "蔬菜类",
        "description": "菌菇清香配青菜，营养搭配，清淡可口",
        "emoji": "🍄🥬", "prepTime": 5, "cookTime": 5,
        "ingredients": [
            {"name": "蘑菇", "amount": 150, "unit": "g"},
            {"name": "生菜", "amount": 300, "unit": "g"},
            {"name": "大蒜", "amount": 10, "unit": "g"},
        ],
        "seasonings": [
            {"name": "生抽", "amount": 10, "unit": "ml"},
            {"name": "蚝油", "amount": 10, "unit": "ml"},
            {"name": "食用油", "amount": 20, "unit": "ml"},
        ],
        "steps": [
            "蘑菇切片，青菜洗净，蒜切片",
            "热锅加油，爆香蒜片",
            "下蘑菇片炒至出水变软",
            "下青菜大火翻炒至变软",
            "加蚝油和生抽调味翻匀即可",
        ],
        "tags": ["快手菜", "素菜", "健康", "清淡"],
        "healthStars": 5, "dietFriendly": True, "dietNote": "低脂低热量高纤维，非常健康的素菜",
        "nutrition": {"calories": 80, "salt": 1.0, "protein": "低蛋白"},
    },
    {
        "id": "g012", "name": "炒土豆丝", "category": "蔬菜类",
        "description": "不酸不辣的原味版，简单好吃，老少皆宜",
        "emoji": "🥔🧅", "prepTime": 10, "cookTime": 5,
        "ingredients": [
            {"name": "土豆", "amount": 400, "unit": "g"},
            {"name": "青椒", "amount": 50, "unit": "g"},
            {"name": "葱", "amount": 10, "unit": "g"},
        ],
        "seasonings": [
            {"name": "生抽", "amount": 10, "unit": "ml"},
            {"name": "食用油", "amount": 20, "unit": "ml"},
            {"name": "盐", "amount": 3, "unit": "g"},
        ],
        "steps": [
            "土豆去皮切细丝，泡水去淀粉，沥干",
            "青椒切丝，葱切段",
            "热锅热油，爆香葱花",
            "下土豆丝大火猛炒2分钟",
            "加青椒丝、生抽、盐",
            "翻炒均匀即可出锅",
        ],
        "tags": ["快手菜", "家常", "素菜", "清淡"],
        "healthStars": 4, "dietFriendly": True, "dietNote": "土豆丝炒制简单，碳水适中，家常健康",
        "nutrition": {"calories": 150, "salt": 1.0, "protein": "低蛋白"},
    },

    # ============================
    # 主食/面食类（约 8 道）
    # ============================
    {
        "id": "n001", "name": "番茄鸡蛋面", "category": "主食类",
        "description": "一碗热汤面，番茄汤底酸香开胃，暖到心底",
        "emoji": "🍅🥚🍜", "prepTime": 5, "cookTime": 15,
        "ingredients": [
            {"name": "面条", "amount": 200, "unit": "g"},
            {"name": "鸡蛋", "amount": 110, "unit": "g"},
            {"name": "番茄", "amount": 300, "unit": "g"},
            {"name": "葱", "amount": 10, "unit": "g"},
        ],
        "seasonings": [
            {"name": "生抽", "amount": 10, "unit": "ml"},
            {"name": "食用油", "amount": 15, "unit": "ml"},
            {"name": "盐", "amount": 3, "unit": "g"},
        ],
        "steps": [
            "番茄切块，鸡蛋打散，葱切花",
            "热锅加油，下番茄炒出汤汁",
            "加水烧开后下面条煮至八分熟",
            "淋入蛋液搅成蛋花",
            "加生抽和盐调味",
            "撒葱花出锅",
        ],
        "tags": ["主食", "快手菜", "汤面", "一人食"],
        "healthStars": 4, "dietFriendly": True, "dietNote": "番茄汤底低脂，适合做减脂期间的碳水摄入",
        "nutrition": {"calories": 400, "salt": 2.2, "protein": "中蛋白"},
    },
    {
        "id": "n002", "name": "青椒肉丝炒饭", "category": "主食类",
        "description": "用冰箱剩食材的美味炒饭，粒粒分明",
        "emoji": "🍚🫑🥩", "prepTime": 5, "cookTime": 10,
        "ingredients": [
            {"name": "大米", "amount": 200, "unit": "g"},
            {"name": "猪肉", "amount": 100, "unit": "g"},
            {"name": "青椒", "amount": 100, "unit": "g"},
            {"name": "鸡蛋", "amount": 55, "unit": "g"},
        ],
        "seasonings": [
            {"name": "生抽", "amount": 15, "unit": "ml"},
            {"name": "老抽", "amount": 5, "unit": "ml"},
            {"name": "食用油", "amount": 25, "unit": "ml"},
            {"name": "盐", "amount": 2, "unit": "g"},
        ],
        "steps": [
            "米饭提前煮好放凉打散",
            "肉切丝加生抽腌制，青椒切丁",
            "热锅多油，炒鸡蛋盛出",
            "下肉丝炒至变色，加青椒丁翻炒",
            "下米饭大火翻炒打散",
            "倒回鸡蛋，加生抽老抽盐翻匀即可",
        ],
        "tags": ["主食", "下饭", "快手菜", "一人食"],
        "healthStars": 3, "dietFriendly": False, "dietNote": "炒饭油多碳水高，减肥期间偶尔吃一次",
        "nutrition": {"calories": 500, "salt": 2.8, "protein": "中蛋白"},
    },
    {
        "id": "n003", "name": "炸酱面", "category": "主食类",
        "description": "老北京经典，肉酱浓郁，黄瓜丝一拌就是天堂",
        "emoji": "🍜🥒", "prepTime": 10, "cookTime": 15,
        "ingredients": [
            {"name": "面条", "amount": 300, "unit": "g"},
            {"name": "猪肉", "amount": 150, "unit": "g"},
            {"name": "黄瓜", "amount": 200, "unit": "g"},
            {"name": "葱", "amount": 10, "unit": "g"},
        ],
        "seasonings": [
            {"name": "豆瓣酱", "amount": 30, "unit": "g"},
            {"name": "生抽", "amount": 10, "unit": "ml"},
            {"name": "老抽", "amount": 5, "unit": "ml"},
            {"name": "料酒", "amount": 10, "unit": "ml"},
            {"name": "白糖", "amount": 5, "unit": "g"},
            {"name": "食用油", "amount": 25, "unit": "ml"},
        ],
        "steps": [
            "猪肉切小丁（半肥半瘦最好），黄瓜切丝",
            "热锅加油，下肥肉丁煸出猪油",
            "下瘦肉丁炒散至变色",
            "下豆瓣酱中小火慢炒出酱香（约5分钟）",
            "加生抽、老抽、料酒、白糖和少量水",
            "小火熬5分钟至酱汁浓稠",
            "面条煮熟捞出过凉",
            "面上浇肉酱，码上黄瓜丝，拌匀开吃",
        ],
        "tags": ["主食", "经典", "北京菜", "下饭"],
        "healthStars": 3, "dietFriendly": False, "dietNote": "酱料油大盐多，减肥期间少酱多黄瓜",
        "nutrition": {"calories": 550, "salt": 4.0, "protein": "中蛋白"},
    },
    {
        "id": "n004", "name": "炒面", "category": "主食类",
        "description": "路边摊的灵魂，自己在家里也能炒出来",
        "emoji": "🍜🥬", "prepTime": 10, "cookTime": 10,
        "ingredients": [
            {"name": "面条", "amount": 200, "unit": "g"},
            {"name": "鸡蛋", "amount": 110, "unit": "g"},
            {"name": "白菜", "amount": 150, "unit": "g"},
            {"name": "火腿肠", "amount": 50, "unit": "g"},
            {"name": "葱", "amount": 10, "unit": "g"},
        ],
        "seasonings": [
            {"name": "生抽", "amount": 15, "unit": "ml"},
            {"name": "老抽", "amount": 10, "unit": "ml"},
            {"name": "蚝油", "amount": 10, "unit": "ml"},
            {"name": "食用油", "amount": 25, "unit": "ml"},
        ],
        "steps": [
            "面条煮至八分熟，捞出过冷水沥干",
            "鸡蛋打散炒熟盛出，白菜切丝，火腿肠切片",
            "热锅多油，下白菜丝和火腿肠翻炒",
            "下面条大火快炒，用筷子辅助打散",
            "加生抽、老抽、蚝油",
            "倒回鸡蛋翻匀，撒葱花出锅",
        ],
        "tags": ["主食", "快手菜", "一人食", "夜市"],
        "healthStars": 3, "dietFriendly": False, "dietNote": "油大碳水高，运动后补充能量合适",
        "nutrition": {"calories": 480, "salt": 3.0, "protein": "中蛋白"},
    },
    {
        "id": "n005", "name": "盖浇饭", "category": "主食类",
        "description": "把菜盖在米饭上，简单粗暴的好吃",
        "emoji": "🍚🥩", "prepTime": 5, "cookTime": 10,
        "ingredients": [
            {"name": "大米", "amount": 200, "unit": "g"},
            {"name": "猪肉", "amount": 150, "unit": "g"},
            {"name": "青椒", "amount": 100, "unit": "g"},
            {"name": "洋葱", "amount": 200, "unit": "g"},
        ],
        "seasonings": [
            {"name": "生抽", "amount": 15, "unit": "ml"},
            {"name": "老抽", "amount": 5, "unit": "ml"},
            {"name": "蚝油", "amount": 10, "unit": "ml"},
            {"name": "淀粉", "amount": 10, "unit": "g"},
            {"name": "料酒", "amount": 10, "unit": "ml"},
            {"name": "食用油", "amount": 20, "unit": "ml"},
        ],
        "steps": [
            "米饭提前煮好",
            "猪肉切片加料酒生抽淀粉腌制",
            "热锅加油，下肉片滑炒至变色",
            "下洋葱丝和青椒块翻炒",
            "加生抽、老抽、蚝油和少量水",
            "水淀粉勾芡使汤汁浓稠",
            "米饭盛入碗中压实倒扣盘中",
            "将炒好的菜浇在米饭上",
        ],
        "tags": ["主食", "下饭", "快手菜", "一人食"],
        "healthStars": 3, "dietFriendly": False, "dietNote": "浇汁含油，减肥期间汁少浇或不浇",
        "nutrition": {"calories": 520, "salt": 2.8, "protein": "中蛋白"},
    },
    {
        "id": "n006", "name": "鸡蛋煎饼", "category": "主食类",
        "description": "早餐必备，简单快手，营养均衡",
        "emoji": "🥞🥚", "prepTime": 5, "cookTime": 10,
        "ingredients": [
            {"name": "鸡蛋", "amount": 110, "unit": "g"},
            {"name": "面粉", "amount": 100, "unit": "g"},
            {"name": "葱", "amount": 10, "unit": "g"},
        ],
        "seasonings": [
            {"name": "食用油", "amount": 15, "unit": "ml"},
            {"name": "盐", "amount": 2, "unit": "g"},
        ],
        "steps": [
            "面粉加水搅成稀糊状，加鸡蛋搅匀",
            "加盐和葱花调味",
            "平底锅刷薄油，中小火加热",
            "倒入面糊摊平成圆形",
            "煎至底部金黄翻面",
            "两面金黄即可出锅",
        ],
        "tags": ["早餐", "快手菜", "主食", "一人食"],
        "healthStars": 4, "dietFriendly": True, "dietNote": "少油煎制，鸡蛋蛋白丰富，早餐健康选择",
        "nutrition": {"calories": 250, "salt": 1.2, "protein": "中蛋白"},
    },
    {
        "id": "n007", "name": "疙瘩汤", "category": "主食类",
        "description": "北方经典面食汤，暖胃养人，生病时最想喝",
        "emoji": "🍲🌾", "prepTime": 10, "cookTime": 10,
        "ingredients": [
            {"name": "面粉", "amount": 100, "unit": "g"},
            {"name": "鸡蛋", "amount": 55, "unit": "g"},
            {"name": "番茄", "amount": 150, "unit": "g"},
            {"name": "葱", "amount": 5, "unit": "g"},
        ],
        "seasonings": [
            {"name": "生抽", "amount": 10, "unit": "ml"},
            {"name": "食用油", "amount": 10, "unit": "ml"},
            {"name": "盐", "amount": 3, "unit": "g"},
        ],
        "steps": [
            "面粉中少量多次滴水，用筷子搅成小面疙瘩",
            "番茄切块，鸡蛋打散",
            "热锅少油炒番茄出汁",
            "加水烧开",
            "均匀撒入面疙瘩，边撒边搅拌防粘",
            "煮3分钟至面疙瘩浮起",
            "淋入蛋液形成蛋花",
            "加生抽和盐调味，撒葱花出锅",
        ],
        "tags": ["汤", "主食", "暖胃", "一人食"],
        "healthStars": 4, "dietFriendly": True, "dietNote": "清淡暖胃，少油低脂，适合胃口不好时吃",
        "nutrition": {"calories": 280, "salt": 1.5, "protein": "中蛋白"},
    },
    {
        "id": "n008", "name": "葱油拌面", "category": "主食类",
        "description": "简单到极致的美味，葱油一浇香飘满屋",
        "emoji": "🍜🧅", "prepTime": 5, "cookTime": 15,
        "ingredients": [
            {"name": "面条", "amount": 200, "unit": "g"},
            {"name": "葱", "amount": 50, "unit": "g"},
        ],
        "seasonings": [
            {"name": "生抽", "amount": 20, "unit": "ml"},
            {"name": "老抽", "amount": 10, "unit": "ml"},
            {"name": "白糖", "amount": 5, "unit": "g"},
            {"name": "食用油", "amount": 40, "unit": "ml"},
        ],
        "steps": [
            "葱切段（葱白和葱绿分开）",
            "冷锅冷油，放入葱段小火慢熬",
            "熬至葱变金褐色（约10分钟），捞出葱段",
            "关火稍凉后加入生抽、老抽、白糖搅匀",
            "面条煮熟捞出",
            "浇葱油拌匀，放上炸过的葱段即可",
        ],
        "tags": ["快手菜", "主食", "一人食", "上海"],
        "healthStars": 3, "dietFriendly": False, "dietNote": "葱油热量较高，但葱油可冰箱保存分次使用",
        "nutrition": {"calories": 420, "salt": 2.5, "protein": "中蛋白"},
    },

    # ============================
    # 汤品类（约 6 道）
    # ============================
    {
        "id": "s001", "name": "紫菜蛋花汤", "category": "汤品类",
        "description": "所有中餐馆的免费汤，自己做更鲜美",
        "emoji": "🥚🍲", "prepTime": 3, "cookTime": 5,
        "ingredients": [
            {"name": "鸡蛋", "amount": 110, "unit": "g"},
            {"name": "葱", "amount": 5, "unit": "g"},
        ],
        "seasonings": [
            {"name": "生抽", "amount": 5, "unit": "ml"},
            {"name": "食用油", "amount": 5, "unit": "ml"},
            {"name": "盐", "amount": 2, "unit": "g"},
        ],
        "steps": [
            "鸡蛋打散，紫菜撕碎（如有干紫菜）",
            "锅中烧水，水开后放入紫菜",
            "转小火，绕圈淋入蛋液",
            "蛋花浮起后加生抽和盐调味",
            "淋少许香油，撒葱花即可",
        ],
        "tags": ["汤", "快手菜", "清淡", "一人食"],
        "healthStars": 5, "dietFriendly": True, "dietNote": "极低热量，饭前喝一碗增加饱腹感",
        "nutrition": {"calories": 80, "salt": 1.0, "protein": "中蛋白"},
    },
    {
        "id": "s002", "name": "冬瓜排骨汤", "category": "汤品类",
        "description": "清淡鲜美，冬瓜入口即化，夏季解暑汤",
        "emoji": "🍈🦴", "prepTime": 10, "cookTime": 60,
        "ingredients": [
            {"name": "排骨", "amount": 300, "unit": "g"},
            {"name": "冬瓜", "amount": 500, "unit": "g"},
            {"name": "生姜", "amount": 15, "unit": "g"},
            {"name": "葱", "amount": 10, "unit": "g"},
        ],
        "seasonings": [
            {"name": "料酒", "amount": 15, "unit": "ml"},
            {"name": "盐", "amount": 4, "unit": "g"},
        ],
        "steps": [
            "排骨斩块，冷水下锅焯水去浮沫洗净",
            "冬瓜去皮去瓤切大块",
            "排骨加姜片、葱段、料酒入锅",
            "加足量水，大火烧开转小火炖40分钟",
            "放入冬瓜块继续炖15分钟至透明",
            "加盐调味，撒葱花即可",
        ],
        "tags": ["汤", "清淡", "夏季", "养身"],
        "healthStars": 4, "dietFriendly": True, "dietNote": "清淡汤品，冬瓜低热量，排骨提供鲜味",
        "nutrition": {"calories": 200, "salt": 2.0, "protein": "高蛋白"},
    },
    {
        "id": "s003", "name": "白菜豆腐汤", "category": "汤品类",
        "description": "清清白白一碗汤，简单纯粹，配什么菜都行",
        "emoji": "🥬🧈🍲", "prepTime": 5, "cookTime": 10,
        "ingredients": [
            {"name": "白菜", "amount": 200, "unit": "g"},
            {"name": "豆腐", "amount": 200, "unit": "g"},
            {"name": "葱", "amount": 5, "unit": "g"},
        ],
        "seasonings": [
            {"name": "食用油", "amount": 5, "unit": "ml"},
            {"name": "盐", "amount": 3, "unit": "g"},
        ],
        "steps": [
            "白菜切段，豆腐切块",
            "锅中少油，下白菜翻炒至变软",
            "加水烧开",
            "下豆腐块煮5分钟",
            "加盐调味，撒葱花即可",
        ],
        "tags": ["汤", "清淡", "快手菜", "素"],
        "healthStars": 5, "dietFriendly": True, "dietNote": "极低热量，吃饱不胖，减肥期间可当主食",
        "nutrition": {"calories": 70, "salt": 1.0, "protein": "中蛋白"},
    },
    {
        "id": "s004", "name": "酸辣汤", "category": "汤品类",
        "description": "开胃暖身，酸辣交织，冬天喝一碗浑身暖和",
        "emoji": "🍲🌶️", "prepTime": 10, "cookTime": 10,
        "ingredients": [
            {"name": "豆腐", "amount": 150, "unit": "g"},
            {"name": "鸡蛋", "amount": 55, "unit": "g"},
            {"name": "木耳", "amount": 20, "unit": "g"},
            {"name": "胡萝卜", "amount": 50, "unit": "g"},
        ],
        "seasonings": [
            {"name": "醋", "amount": 25, "unit": "ml"},
            {"name": "生抽", "amount": 10, "unit": "ml"},
            {"name": "淀粉", "amount": 15, "unit": "g"},
            {"name": "食用油", "amount": 10, "unit": "ml"},
            {"name": "盐", "amount": 3, "unit": "g"},
        ],
        "steps": [
            "豆腐木耳胡萝卜切丝",
            "锅中少油炒胡萝卜丝",
            "加水烧开，下豆腐丝木耳丝",
            "加生抽、醋、盐",
            "转小火，淋入蛋液搅成蛋花",
            "水淀粉勾芡，淋少许香油出锅",
        ],
        "tags": ["汤", "开胃", "快手菜"],
        "healthStars": 4, "dietFriendly": True, "dietNote": "酸辣味用醋和天然辣味，热量不高",
        "nutrition": {"calories": 120, "salt": 2.0, "protein": "中蛋白"},
    },
    {
        "id": "s005", "name": "玉米排骨汤", "category": "汤品类",
        "description": "玉米的甜配上排骨的鲜，汤甜肉香",
        "emoji": "🌽🦴", "prepTime": 10, "cookTime": 60,
        "ingredients": [
            {"name": "排骨", "amount": 300, "unit": "g"},
            {"name": "玉米", "amount": 500, "unit": "g"},
            {"name": "胡萝卜", "amount": 100, "unit": "g"},
            {"name": "生姜", "amount": 10, "unit": "g"},
        ],
        "seasonings": [
            {"name": "料酒", "amount": 15, "unit": "ml"},
            {"name": "盐", "amount": 4, "unit": "g"},
        ],
        "steps": [
            "排骨焯水洗净，玉米切段，胡萝卜切滚刀块",
            "排骨加姜片料酒，冷水入锅",
            "大火烧开撇去浮沫转小火",
            "炖30分钟后加入玉米和胡萝卜",
            "继续炖30分钟至排骨软烂",
            "加盐调味即可",
        ],
        "tags": ["汤", "清淡", "养身", "家常"],
        "healthStars": 4, "dietFriendly": True, "dietNote": "清炖做法少油，玉米提供天然甜味不需加糖",
        "nutrition": {"calories": 280, "salt": 1.8, "protein": "高蛋白"},
    },
    {
        "id": "s006", "name": "番茄蛋汤", "category": "汤品类",
        "description": "三分钟搞定的家常汤，酸甜开胃",
        "emoji": "🍅🥚🍲", "prepTime": 3, "cookTime": 5,
        "ingredients": [
            {"name": "番茄", "amount": 300, "unit": "g"},
            {"name": "鸡蛋", "amount": 110, "unit": "g"},
            {"name": "葱", "amount": 5, "unit": "g"},
        ],
        "seasonings": [
            {"name": "食用油", "amount": 10, "unit": "ml"},
            {"name": "盐", "amount": 2, "unit": "g"},
        ],
        "steps": [
            "番茄切块，鸡蛋打散",
            "热锅少油，下番茄炒出汁",
            "加水烧开煮2分钟",
            "转小火淋入蛋液形成蛋花",
            "加盐调味，撒葱花即可",
        ],
        "tags": ["汤", "快手菜", "一人食"],
        "healthStars": 5, "dietFriendly": True, "dietNote": "低热量番茄汤底，非常适合减肥期间",
        "nutrition": {"calories": 100, "salt": 1.0, "protein": "中蛋白"},
    },

    # ============================
    # 凉拌/快手类（约 4 道）
    # ============================
    {
        "id": "l001", "name": "凉拌木耳", "category": "凉拌类",
        "description": "清爽Q弹，木耳脆嫩，夏天开胃菜",
        "emoji": "🍄❄️", "prepTime": 20, "cookTime": 5,
        "ingredients": [
            {"name": "木耳", "amount": 30, "unit": "g"},
            {"name": "黄瓜", "amount": 200, "unit": "g"},
            {"name": "大蒜", "amount": 10, "unit": "g"},
            {"name": "干辣椒", "amount": 5, "unit": "g"},
        ],
        "seasonings": [
            {"name": "生抽", "amount": 15, "unit": "ml"},
            {"name": "醋", "amount": 15, "unit": "ml"},
            {"name": "白糖", "amount": 5, "unit": "g"},
            {"name": "食用油", "amount": 10, "unit": "ml"},
        ],
        "steps": [
            "木耳提前泡发（冷水2小时），去根撕小朵",
            "开水焯木耳2分钟，捞出过冷水",
            "黄瓜拍碎切段",
            "调汁：生抽+醋+白糖+蒜末",
            "木耳黄瓜放大碗中浇汁拌匀",
            "干辣椒剪段放上面",
            "热油烧至冒烟浇在辣椒上激香",
        ],
        "tags": ["凉菜", "夏季", "快手菜", "开胃"],
        "healthStars": 5, "dietFriendly": True, "dietNote": "极低热量高纤维，木耳清理肠道",
        "nutrition": {"calories": 60, "salt": 1.2, "protein": "低蛋白"},
    },
    {
        "id": "l002", "name": "糖拌番茄", "category": "凉拌类",
        "description": "童年的味道，冰凉甜蜜，最简单的甜品",
        "emoji": "🍅🍬", "prepTime": 3, "cookTime": 0,
        "ingredients": [
            {"name": "番茄", "amount": 300, "unit": "g"},
        ],
        "seasonings": [
            {"name": "白糖", "amount": 15, "unit": "g"},
        ],
        "steps": [
            "番茄洗净切片",
            "码在盘中",
            "均匀撒上白糖",
            "放入冰箱冷藏10分钟更佳",
        ],
        "tags": ["凉菜", "甜品", "夏季", "无需开火", "新手友好"],
        "healthStars": 3, "dietFriendly": False, "dietNote": "番茄健康但加糖增加了热量，减肥期间少放糖",
        "nutrition": {"calories": 80, "salt": 0.02, "protein": "低蛋白"},
    },
    {
        "id": "l003", "name": "拍黄瓜", "category": "凉拌类",
        "description": "拍一拍，拌一拌，两分钟搞定的万能凉菜",
        "emoji": "🥒🔪", "prepTime": 3, "cookTime": 0,
        "ingredients": [
            {"name": "黄瓜", "amount": 400, "unit": "g"},
            {"name": "大蒜", "amount": 10, "unit": "g"},
        ],
        "seasonings": [
            {"name": "生抽", "amount": 15, "unit": "ml"},
            {"name": "醋", "amount": 15, "unit": "ml"},
            {"name": "白糖", "amount": 3, "unit": "g"},
            {"name": "食用油", "amount": 10, "unit": "ml"},
        ],
        "steps": [
            "黄瓜洗净，用刀背拍裂（听到清脆的碎裂声）",
            "切成小段放入碗中",
            "蒜切末撒在黄瓜上",
            "生抽+醋+白糖调汁浇入",
            "烧热油浇在蒜末上",
            "拌匀腌制3分钟入味",
        ],
        "tags": ["凉菜", "快手菜", "夏季", "无需开火"],
        "healthStars": 5, "dietFriendly": True, "dietNote": "零热量负担，最健康的凉菜选择",
        "nutrition": {"calories": 50, "salt": 1.0, "protein": "低蛋白"},
    },

    # ============================
    # 补充：更多家常菜
    # ============================
]

# 统计
print(f"食谱库共 {len(RECIPES)} 道菜") if __name__ == "__main__" else None
